### ISSUE TITLE
All in one install failed

### ISSUE THREAD

**Issue by nbit99** [yunionio/cloudpods#14890]
**What happened**:
All in one install failed,registry.cn-beijing.aliyuncs.com/yunion/traefik:v1.7 not found
**Environment**:
centos7.9
- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):

```
TASK [primary-master-node/setup_k8s : load local images if exist; it might take a few minutes...] *****************
changed: [192.168.1.108]

TASK [primary-master-node/setup_k8s : Pull ocadm images on node] **************************************************
fatal: [192.168.1.108]: FAILED! => {"changed": true, "cmd": ["/opt/yunion/bin/ocadm", "config", "images", "pull", "--image-repository", "registry.cn-beijing.aliyuncs.com/yunion", "--onecloud-version", "v3.9.1", "--operator-version", "v3.9.1"], "delta": "0:00:19.426483", "end": "2022-08-31 10:33:44.486576", "msg": "non-zero return code", "rc": 1, "start": "2022-08-31 10:33:25.060093", "stderr": "failed to pull image "registry.cn-beijing.aliyuncs.com/yunion/traefik:v1.7": output: Error response from daemon: manifest for registry.cn-beijing.aliyuncs.com/yunion/traefik:v1.7 not found: manifest unknown: manifest unknown\n, error: exit status 1", "stderr_lines": ["failed to pull image "registry.cn-beijing.aliyuncs.com/yunion/traefik:v1.7": output: Error response from daemon: manifest for registry.cn-beijing.aliyuncs.com/yunion/traefik:v1.7 not found: manifest unknown: manifest unknown", ", error: exit status 1"], "stdout": "[config/images] Pulling registry.cn-beijing.aliyuncs.com/yunion/kube-apiserver:v1.15.8\n[config/images] Pulled registry.cn-beijing.aliyuncs.com/yunion/kube-apiserver:v1.15.8\n[config/images] Pulling registry.cn-beijing.aliyuncs.com/yunion/kube-controller-manager:v1.15.8\n[config/images] Pulled registry.cn-beijing.aliyuncs.com/yunion/kube-controller-manager:v1.15.8\n[config/images] Pulling registry.cn-beijing.aliyuncs.com/yunion/kube-scheduler:v1.15.8\n[config/images] Pulled registry.cn-beijing.aliyuncs.com/yunion/kube-scheduler:v1.15.8\n[config/images] Pulling registry.cn-beijing.aliyuncs.com/yunion/kube-proxy:v1.15.8\n[config/images] Pulled registry.cn-beijing.aliyuncs.com/yunion/kube-proxy:v1.15.8\n[config/images] Pulling registry.cn-beijing.aliyuncs.com/yunion/pause:3.1\n[config/images] Pulled registry.cn-beijing.aliyuncs.com/yunion/pause:3.1\n[config/images] Pulling registry.cn-beijing.aliyuncs.com/yunion/etcd:3.4.6\n[config/images] Pulled registry.cn-beijing.aliyuncs.com/yunion/etcd:3.4.6\n[config/images] Pulling registry.cn-beijing.aliyuncs.com/yunion/coredns:1.3.1\n[config/images] Pulled registry.cn-beijing.aliyuncs.com/yunion/coredns:1.3.1\n[config/images] Pulling registry.cn-beijing.aliyuncs.com/yunion/calico-node:v3.12.1\n[config/images] Pulled registry.cn-beijing.aliyuncs.com/yunion/calico-node:v3.12.1\n[config/images] Pulling registry.cn-beijing.aliyuncs.com/yunion/calico-cni:v3.12.1\n[config/images] Pulled registry.cn-beijing.aliyuncs.com/yunion/calico-cni:v3.12.1\n[config/images] Pulling registry.cn-beijing.aliyuncs.com/yunion/local-path-provisioner:v0.0.11\n[config/images] Pulled registry.cn-beijing.aliyuncs.com/yunion/local-path-provisioner:v0.0.11\n[config/images] Pulling registry.cn-beijing.aliyuncs.com/yunion/traefik:v1.7", "stdout_lines": ["[config/images] Pulling registry.cn-beijing.aliyuncs.com/yunion/kube-apiserver:v1.15.8", "[config/images] Pulled registry.cn-beijing.aliyuncs.com/yunion/kube-apiserver:v1.15.8", "[config/images] Pulling registry.cn-beijing.aliyuncs.com/yunion/kube-controller-manager:v1.15.8", "[config/images] Pulled registry.cn-beijing.aliyuncs.com/yunion/kube-controller-manager:v1.15.8", "[config/images] Pulling registry.cn-beijing.aliyuncs.com/yunion/kube-scheduler:v1.15.8", "[config/images] Pulled registry.cn-beijing.aliyuncs.com/yunion/kube-scheduler:v1.15.8", "[config/images] Pulling registry.cn-beijing.aliyuncs.com/yunion/kube-proxy:v1.15.8", "[config/images] Pulled registry.cn-beijing.aliyuncs.com/yunion/kube-proxy:v1.15.8", "[config/images] Pulling registry.cn-beijing.aliyuncs.com/yunion/pause:3.1", "[config/images] Pulled registry.cn-beijing.aliyuncs.com/yunion/pause:3.1", "[config/images] Pulling registry.cn-beijing.aliyuncs.com/yunion/etcd:3.4.6", "[config/images] Pulled registry.cn-beijing.aliyuncs.com/yunion/etcd:3.4.6", "[config/images] Pulling registry.cn-beijing.aliyuncs.com/yunion/coredns:1.3.1", "[config/images] Pulled registry.cn-beijing.aliyuncs.com/yunion/coredns:1.3.1", "[config/images] Pulling registry.cn-beijing.aliyuncs.com/yunion/calico-node:v3.12.1", "[config/images] Pulled registry.cn-beijing.aliyuncs.com/yunion/calico-node:v3.12.1", "[config/images] Pulling registry.cn-beijing.aliyuncs.com/yunion/calico-cni:v3.12.1", "[config/images] Pulled registry.cn-beijing.aliyuncs.com/yunion/calico-cni:v3.12.1", "[config/images] Pulling registry.cn-beijing.aliyuncs.com/yunion/local-path-provisioner:v0.0.11", "[config/images] Pulled registry.cn-beijing.aliyuncs.com/yunion/local-path-provisioner:v0.0.11", "[config/images] Pulling registry.cn-beijing.aliyuncs.com/yunion/traefik:v1.7"]}

PLAY RECAP ********************************************************************************************************
192.168.1.1: ok=63 changed=16 unreachable=0 failed=1 skipped=15 rescued=0 ignored=0
```

config-allinone.yml

```
# mariadb_node 表示需要部署 mariadb 服务的节点
mariadb_node:
  # 待部署节点 ip
  hostname: 192.168.1.108
  # 待部署节点登录用户
  user: root
  # mariadb 的用户
  db_user: root
  # mariadb 用户密码
  db_password: root
# primary_master_node 表示运行 k8s 和 Cloudpods 服务的节点
primary_master_node:
  hostname: 192.168.1.108
  user: root
  # 数据库连接地址
  db_host: 192.168.1.108
  # 数据库用户
  db_user: root
  # 数据库密码
  db_password: root
  # k8s 控制节点的 ip
  controlplane_host: 192.168.1.108
  # k8s 控制节点的端口
  controlplane_port: "6443"
  # Cloudpods 版本
  onecloud_version: v3.9.1
  # Cloudpods 登录用户
  onecloud_user: admin
  # Cloudpods 登录用户密码
  onecloud_user_password: admin@123
  # 该节点作为 Cloudpods 私有云计算节点
  as_host: true
  # 启用 minio 作为后端对象存储
  enable_minio: true
  registry_mirrors:
    - https://lje6zxpk.mirror.aliyuncs.com
    - https://lms7sxqp.mirror.aliyuncs.com

```
