### ISSUE TITLE
scheduler 的 forecast api 返回的 reasons 不全

### ISSUE THREAD

**Issue by zexi** [yunionio/cloudpods#16174]
**What happened**:

调度器 forecast api 没有返回所有宿主机被过滤的原因，结果如下：

```yaml
[root@open-install01 ~]# climc scheduler-history-show --log --raw 1678245744596
consuming: 179.4942ms
error: ""
input: '{"backup":false,"baremetal_disk_configs":[{"conf":"none","count":0,"type":"hybrid"}],"best_effort":false,"change_config":false,"count":1,"details":false,"disks":[{"backend":"local","cache":"writeback","disk_type":"sys","driver":"scsi","format":"qcow2","image_id":"ff3ad6cd-de89-4373-80c8-197e3a88eb35","index":0,"medium":"ssd","size":40960},{"backend":"local","cache":"writeback","disk_type":"data","driver":"scsi","format":"qcow2","index":1,"medium":"ssd","size":10240}],"domain_id":"default","has_isolated_device":false,"host_id":"c4546301-4168-42d1-8857-95857ec2f2c6","host_mem_page_size":0,"hypervisor":"hypervisor","live_migrate":false,"name":"qtt-test4","nets":[{"address":"10.0.1.249","bw_limit":1000,"domain_id":"default","driver":"virtio","exit":false,"ifname":"lxjnet-249","index":0,"mac":"00:22:b3:09:ac:e4","net_type":"guest","network":"6ce598e9-2e9b-4c97-8169-60b05db802ea","num_queues":0,"private":false,"project_id":"48dacc96a11b458f8e5c6b3ec5c14734","require_designated_ip":false,"require_teaming":false,"reserved":false,"standby_addr_count":0,"standby_port_count":0,"try_teaming":false,"vip":false,"wire":"4d000a5c-1f4a-4ad4-87df-b899c0f2a029"}],"os_arch":"x86","project_id":"48dacc96a11b458f8e5c6b3ec5c14734","record_to_history":false,"resource_type":"shared","reuse_network":true,"suggestion":false,"suggestion_all":false,"suggestion_limit":100,"vcpu_count":1,"vmem_size":1024}'
output: |-
  {
    "Result": null,
    "ForecastResult": {
      "can_create": false,
      "candidates": null,
      "req_count": 1,
      "allow_count": 0,
      "not_allow_reasons": [
        "Out of resource"
      ],
      "filtered_candidates": [
        {
          "id": "c4546301-4168-42d1-8857-95857ec2f2c6",
          "name": "qtt-test-10-127-190-195",
          "filter_name": "host_migrate",
          "reasons": [
            "host_id specified for migration"
          ]
        }
      ]
    },
    "TestResult": null
  }
session_id: "1678245744596"
tasks:
- capacity_map:
    7b9c16f7-1b23-40a6-8d38-b339873141bd:
      MinValue: 12
      Values:
        host_cpu:
          Value: 94
        host_memory:
          Value: 12
        host_storage:
          Value: 4294967295
    c4546301-4168-42d1-8857-95857ec2f2c6:
      MinValue: 0
      Values:
        host_migrate:
          Value: 0
  consuming: 179.43076ms
  data:
    __meta__: null
    ChangeConfig: false
    HasIsolatedDevice: false
    InstanceGroupsDetail: null
    PendingUsages: null
    Raw: '{"backup":false,"baremetal_disk_configs":[{"conf":"none","count":0,"type":"hybrid"}],"best_effort":false,"change_config":false,"count":1,"details":false,"disks":[{"backend":"local","cache":"writeback","disk_type":"sys","driver":"scsi","format":"qcow2","image_id":"ff3ad6cd-de89-4373-80c8-197e3a88eb35","index":0,"medium":"ssd","size":40960},{"backend":"local","cache":"writeback","disk_type":"data","driver":"scsi","format":"qcow2","index":1,"medium":"ssd","size":10240}],"domain_id":"default","has_isolated_device":false,"host_id":"c4546301-4168-42d1-8857-95857ec2f2c6","host_mem_page_size":0,"hypervisor":"hypervisor","live_migrate":false,"name":"qtt-test4","nets":[{"address":"10.0.1.249","bw_limit":1000,"domain_id":"default","driver":"virtio","exit":false,"ifname":"lxjnet-249","index":0,"mac":"00:22:b3:09:ac:e4","net_type":"guest","network":"6ce598e9-2e9b-4c97-8169-60b05db802ea","num_queues":0,"private":false,"project_id":"48dacc96a11b458f8e5c6b3ec5c14734","require_designated_ip":false,"require_teaming":false,"reserved":false,"standby_addr_count":0,"standby_port_count":0,"try_teaming":false,"vip":false,"wire":"4d000a5c-1f4a-4ad4-87df-b899c0f2a029"}],"os_arch":"x86","project_id":"48dacc96a11b458f8e5c6b3ec5c14734","record_to_history":false,"resource_type":"shared","reuse_network":true,"suggestion":false,"suggestion_all":false,"suggestion_limit":100,"vcpu_count":1,"vmem_size":1024}'
    UserCred:
      TokenCredential:
        Context:
          ip: 10.103.133.74
          source: srv
        Domain: Default
        DomainId: default
        Expires: "2023-03-09T02:00:27Z"
        ProjectDomain: Default
        ProjectDomainId: default
        RoleIds: 603d89856e764b298758a1ebcf73d60f
        Roles: admin
        Token: gAAAAABkB-w8fGMV7gcZTI1P3OdTN2z5URLAYHIXU51Fcmtf_ZqQHmnW6Vtyu2d1MkjB-yxy-mKiHVq7qoQkKXqaZQ2JO_RWaPmCBfaGmP6uOoBJ0OseJ2yYne-agHUFeKh7z0dqYJtfhJXQSmDv3cRFKTHy6TKSebCavrbr34ZuWsp-9iMmqptGVIRoZwpNV7EnNkEFdVPf
        User: regionadmin
        UserId: 20f4bf7c4db2406680b8696e8f7bfa21
        tenant: system
        tenant_id: 48dacc96a11b458f8e5c6b3ec5c14734
    backup: false
    baremetal_disk_configs:
    - conf: none
      count: 0
      driver: ""
      range: null
      size: null
      splits: ""
      type: hybrid
    best_effort: false
    candidates: []
    cdrom: ""
    count: 1
    cpu_desc: ""
    cpu_microcode: ""
    cpu_mode: ""
    details: false
    disks:
    - backend: local
      backup_id: ""
      boot_index: null
      cache: writeback
      disk_id: ""
      disk_type: sys
      driver: scsi
      existing_path: ""
      format: qcow2
      fs: ""
      image_encrypt_key_id: ""
      image_id: ff3ad6cd-de89-4373-80c8-197e3a88eb35
      image_properties: null
      index: 0
      medium: ssd
      mountpoint: ""
      os_arch: ""
      schedtags: []
      size: 40960
      snapshot_id: ""
      storage_id: ""
    - backend: local
      backup_id: ""
      boot_index: null
      cache: writeback
      disk_id: ""
      disk_type: data
      driver: scsi
      existing_path: ""
      format: qcow2
      fs: ""
      image_encrypt_key_id: ""
      image_id: ""
      image_properties: null
      index: 1
      medium: ssd
      mountpoint: ""
      os_arch: ""
      schedtags: []
      size: 10240
      snapshot_id: ""
      storage_id: ""
    domain_id: default
    for_guests: null
    group_releations: null
    groups: null
    guest_status: ""
    host_id: c4546301-4168-42d1-8857-95857ec2f2c6
    host_mem_page_size: 0
    hypervisor: hypervisor
    id: ""
    ignore_filters: {}
    instance_backup_id: ""
    instance_snapshot_id: ""
    instance_type: ""
    is_container: false
    isolated_devices: null
    live_migrate: false
    name: qtt-test4
    nets:
    - address: 10.0.1.249
      address6: ""
      bw_limit: 1000
      domain_id: default
      driver: virtio
      exit: false
      ifname: lxjnet-249
      index: 0
      mac: 00:22:b3:09:ac:e4
      net_type: guest
      network: 6ce598e9-2e9b-4c97-8169-60b05db802ea
      num_queues: 0
      private: false
      project_id: 48dacc96a11b458f8e5c6b3ec5c14734
      require_designated_ip: false
      require_teaming: false
      reserved: false
      schedtags: []
      sriov_device: null
      standby_addr_count: 0
      standby_port_count: 0
      try_teaming: false
      vip: false
      wire: 4d000a5c-1f4a-4ad4-87df-b899c0f2a029
    os_arch: x86
    prefer_backup_host: ""
    prefer_host_id: ""
    prefer_manager_id: ""
    prefer_region_id: ""
    prefer_wire_id: ""
    prefer_zone_id: ""
    project_id: 48dacc96a11b458f8e5c6b3ec5c14734
    record_to_history: false
    required_candidates: 1
    resource_type: shared
    reuse_network: true
    schedtags: []
    session_id: "1678245744596"
    skip_cpu_check: null
    skip_kernel_check: null
    sku: ""
    suggestion: true
    suggestion_all: true
    suggestion_details: true
    suggestion_limit: 100
    tag: ""
    target_host_kernel: ""
    type: ""
    vcpu_count: 1
    vmem_size: 1024
  error: ""
  logs:
  - 'Success: open-install01-10-127-100-240:7b9c16f7-1b23-40a6-8d38-b339873141bd [class_metadata,host_cpu,host_domain,host_hypervisor_runtime,host_memory,host_migrate,host_schedtag,host_status] '
  - 'Failed: open-install01-10-127-100-240:7b9c16f7-1b23-40a6-8d38-b339873141bd [host_storage]
    host_storage: storage "host_10.127.100.240_local_storage_0" free size 15045 less
    than max request 40960, use reserverd false, free_capacity(15045), actual_free_capacity(190699)'
  - 'Success: qtt-test-10-127-190-195:c4546301-4168-42d1-8857-95857ec2f2c6 [host_hypervisor_runtime,host_schedtag,host_status] '
  - 'Failed: qtt-test-10-127-190-195:c4546301-4168-42d1-8857-95857ec2f2c6 [host_migrate]
    host_migrate: host_id specified for migration'
  result:
    ForecastResult:
      allow_count: 0
      can_create: false
      candidates: null
      filtered_candidates:
      - filter_name: host_migrate
        id: c4546301-4168-42d1-8857-95857ec2f2c6
        name: qtt-test-10-127-190-195
        reasons:
        - host_id specified for migration
      not_allow_reasons:
      - Out of resource
      req_count: 1
    Result: null
    TestResult: null
  status: success
  time: "2023-03-08 03:22:24"
  type: hypervisor
time: "2023-03-08 03:22:24"
```

**Environment**:

- OS (e.g. `cat /etc/os-release`): centos 7
- Service Version (e.g. `kubectl exec -n onecloud $(kubectl get pods -n onecloud | grep climc | awk '{print $1}') -- climc version-list`):
- Version (e.g. `climc version-list`):
|      Field      |                    Value                     |
+-----------------+----------------------------------------------+
| ansible         | (23030611)                                   |
| autoupdate      | (23022002)                                   |
| cloudevent      | (23030611)                                   |
| cloudid         | (23030611)                                   |
| cloudmeta       | ci/ucloud-basic-data-support(aedc811)        |
| cloudmon        | (23030611)                                   |
| cloudproxy      | release/3.10(bb5c1b06c223030612)             |
| compute_v2      | (23030611)                                   |
| devtool         | (23030611)                                   |
| etcd            | {"etcdserver":"3.4.6","etcdcluster":"3.4.0"} |
| identity        | (23030611)                                   |
| image           | (23030611)                                   |
| influxdb        | 404 page not found                           |
| itsm            | v3.10.0-20230305.0(cd96817)                  |
| k8s             | heads/v3.10.0-20230305.0(b2370cf23030611)    |
| log             | (23030611)                                   |
| meter           | (23030611)                                   |
| monitor         | (23030611)                                   |
| notify          | addHcsoMonitor(5754ac605523030707)           |
| report          | (23030611)                                   |
| scheduledtask   | (23030611)                                   |
| scheduler       | (23030611)                                   |
| suggestion      | (23030611)                                   |
| torrent-tracker | <title>Not Found</title>                     |
| vpcagent        | release/3.10(bb5c1b06c223030612)             |
| webconsole      | (23030611)                                   |
| websocket       | (23030611)                                   |
| yunionagent     | (23030611)                                   |
| yunionconf      | (23030611)                                   |
+-----------------+----------------------------------------------+
