### ISSUE TITLE
[求助/Help]无法清理镜像回收站

### ISSUE THREAD

**Issue by shuoshadow** [yunionio/cloudpods#16664]
之前因为不知道镜像有回收站，删除镜像后发现机器上目录下的镜像没有清理，就手动删除了。然后发现了镜像回收站可以清理，但是点击清理后一直处于正在删除中的状态，应该怎么解决？
![image](https://user-images.githubusercontent.com/10016360/232452712-77c1ada5-e75f-4280-89d0-57c633d18687.png)

**Comment by hoganlxj** [comment]
1.可以再点击清除试下，看是否清除
2.可以在部署cloudpods的机器上，执行kubectl get pods -n onecloud | grep glance | awk '{print $1}' |xargs kubectl logs -n onecloud  |less   看下是否有error相关的信息

**Comment by shuoshadow** [comment]
> 1.可以再点击清除试下，看是否清除 2.可以在部署cloudpods的机器上，执行kubectl get pods -n onecloud | grep glance | awk '{print $1}' |xargs kubectl logs -n onecloud |less 看下是否有error相关的日志没

1、再次点击清除无效
2、glance日志有报错内容如下：
[error 2023-04-17 11:19:30 tasks.(*ImageDeleteTask).startDeleteImage(image_delete_task.go:69)] fail to remove host-convert-v39.qcow2 remove subimg : removeFiles: s3 client not init

这应该是之前我用官网文档部署allinone，文档上使用了minio存储镜像导致的原因。后面我更改minio为本地存储了，使用的是`climc service-config-edit glance`命令，修改了一些配置。目前的配置文件如下：
```yaml
default:
  auth_token_cache_size: 2048
  calculate_quota_usage_interval_seconds: 900
  cron_job_worker_count: 4
  debug_client: false
  default_image_quota: 10
  enable_pending_delete: true
  enable_torrent_service: false
  filesystem_store_datadir: /opt/cloud/workspace/data/glance/images
  historical_unique_name: false
  pending_delete_check_seconds: 3600
  pending_delete_expire_seconds: 259200
  pending_delete_max_clean_batch_size: 50
  policy_worker_count: 1
  query_offset_optimization: false
  rbac_debug: false
  rbac_policy_refresh_interval_seconds: 30
  request_worker_count: 8
  s3_access_key: minioadmin
  s3_bucket_name: onecloud-images
  s3_check_image_status: false
  s3_endpoint: minio.onecloud-minio:9000
  s3_mount_point: /opt/cloud/workspace/data/glance/s3images
  s3_secret_key: yunionminio@admin
  s3_use_ssl: false
  storage_driver: local
  target_image_formats:
  - qcow2
  - vmdk
  task_worker_count: 4
  tenant_cache_expire_seconds: 900
  torrent_client_path: /opt/yunion/bin/torrent
  torrent_store_dir: /opt/cloud/workspace/data/glance/torrents
```
现在应该怎么处理？
