### ISSUE TITLE
[Feature] [OSPP2023] Support for deploying Cloudpods on Ubuntu 22.04（支持将 Cloudpods 融合云平台部署在 Ubuntu 22.04 发行版）

### ISSUE THREAD

**Issue by niconical** [yunionio/cloudpods#17543]
## 支持将 Cloudpods 融合云平台部署在 Ubuntu 22.04 发行版

导师：[Zexi Li](https://github.com/zexi)
中选学生：[Cuih (niconical)](https://github.com/niconical)

### 项目简述

目前 Cloudpods 使用 [ocboot](http://github.com/yunionio/ocboot) 这个部署工具，能够以分布式多节点的方式部署运行在 CentOS 7 、 Debian 10 和 Kylin 等 Linux 发行版上。另外服务分布式多节点运行的架构是依赖 Kubernetes 作为底座的，所以 ocboot 调用 ansible 部署平台的时候，会优先部署一套 Kubernetes ，最后再把各个服务以容器化的方式运行在 Kubernetes 上，这样底层的节点可以是不同架构的不通发行版。

Ubuntu 是一个使用很普及的 Linux 发行版，该项目需要能够在 ocboot 工具里面适配 Ubuntu 发行版的部署，让 Cloudpods 相关服务运行在 Ubuntu 22.04 LTS 发行版上。

部署服务的方式主要是使用 python 读取配置文件，然后生成 ansible 的 inventory ，最后调用 ansible 运行相关 playbook 完成服务的部署。

### 项目产出要求

- 将 Cloudpods 融合云部署运行在 Ubuntu 22.04 LTS 发行版上
- 实现功能，以 PR 的方式提交代码到 [ocboot upstream](http://github.com/yunionio/ocboot) 仓库

### 参考
- [OSPP2023支持将 Cloudpods 融合云平台部署在 Ubuntu 22.04 发行版](https://summer-ospp.ac.cn/org/prodetail/239660196?list=org&navpage=org)

**Comment by niconical** [comment]
I will try to submit my proposal under this issue in both Chinese and English. @zexi

**Comment by niconical** [comment]
## 项目开发方案

### 1.1 待修改的源代码

- onecloud/roles/common/tasks/ubuntu_22_aarch64.yml
- onecloud/roles/common/tasks/ubuntu_22_x86_64.yml
- onecloud/roles/mariadb/tasks/ubuntu-aarch64.yml
- onecloud/roles/mariadb/tasks/ubuntu-x86_64.yml
- onecloud/roles/utils/detect-os/vars/debian-10.aarch64.yml
- onecloud/roles/utils/detect-os/vars/debian.yml
- onecloud/roles/utils/detect-os/vars/ubuntu-22.aarch64.yml
- onecloud/roles/utils/detect-os/vars/ubuntu-22.x86_64.yml
- onecloud/roles/utils/detect-os/vars/uniontech_os_server_20_enterprise-20.aarch64.yml
- onecloud/roles/utils/detect-os/vars/uniontech_os_server_20_enterprise-20.x86_64.yml
- onecloud/roles/utils/misc-check/tasks/os.yml
- run.py

#### 1.1.1 run.py

`run.py` 为了兼容 Ubuntu 22.04 LTS 需要对下列函数做如下改动（以类似`git diff`的形式显示改动）：

1. 修改`install_packages()`方法

```python
def install_packages(pkgs):
    if os.system('grep -Pq "Kylin Linux Advanced Server|CentOS Linux|openEuler" /etc/os-release') == 0:
        return os.system("yum install -y %s" % (" ".join(pkgs)))
-   elif os.system('grep -wq "Debian GNU/Linux" /etc/os-release') == 0:
+   elif os.system('grep -Pq "Debian GNU/Linux|Ubuntu" /etc/os-release') == 0:
  return os.system("apt install -y %s" % (" ".join(pkgs)))
 else:
  print("Unsupported OS")
  return 255
```

2. 在 Ubuntu 22.04 LTS 版本中删除 `python2-pyyaml` 和 `PyYAML`

目前代码多处在安装环境时，需要安装 `python2-pyyaml`包，但是目前有几个证据证明不需要在 Ubuntu 22.04 LTS 机器上安装此包：

- pyyaml 早在2021年已经[不再维护](https://github.com/yaml/pyyaml/issues/476) Python2 版本
- Ubuntu 22.04 LTS 中[默认使用](https://ubuntuforums.org/showthread.php?t=2472347) Python 3
- ocboot 依赖 [pip3](https://github.com/yunionio/ocboot/blob/56cb62c46b7200311f15c5a77496c5d474dbbb54/run.py#L40)

以下以`install_ansible()`作为修改示例

```python
def install_ansible():
-  for pkg in ['python2-pyyaml', 'PyYAML']:
-       install_packages([pkg])
+   if os.system('grep -wq "Ubuntu" /etc/os-release') == 0:
+       install_packages(["python3-yaml"])
+   else:
+       for pkg in ['python2-pyyaml', 'PyYAML']:
+           install_packages([pkg])
...
```

#### 1.1.2 修改 misc-check/tasks/os.yml

[严格界定所支持的os（centos/kylin/debian/uos/euler）及其版本范围 #842](https://github.com/yunionio/ocboot/pull/842) 中新增了 os.yml 文件进行更为严格的操作系统版本控制，所以为了支持 Ubuntu，需要在该文件中添加相应版本。

```yaml
+     ubuntu:
+       ansible_distribution_name: "Ubuntu"
+       conditions:
+         - "'{{ ansible_distribution_version }}' is version('22.04', '>=')"
```

#### 1.1.2 修改 roles

1. utils/detect-os

因为不同操作系统上的宿主机需要安装不同软件，而且 ocboot 安装了一部分自有软件（例如 yunion-climc, yunion-executor 等），因此为了支持 Ubuntu 22.04 LTS 操作系统版本，需要 Cloudpods 提供官方软件源。根据官网文档，目前 Cloudpods 支持以下软件源：

- `CentOS 7`: aarch64, x86_64
- `Kylin V10`: aarch64, x86_64
- `Debian 10`: aarch64, x86_64

因为 UOS V20 基于 Debian 10.x，因此在 ocboot 中使用和 Debian 10 [相同的软件源](https://github.com/yunionio/ocboot/pull/64/files#r609558022)。因此，为了需要支持 Ubuntu 22.04 LTS，**需要提供官方 Ubuntu 22.04 LTS jammy 软件源**。
Debian 10 上的软件依赖与 Ubuntu 22.04 LTS 类似，因此本方案在 utils/detect-os/vars下新建名为 ubuntu-20.x86_64.yml 与 ubuntu-20.aarch64.yml 文件，文件内容为需要安装的软件包，内容参照 UOS 与 Debian 10。
以下为 ubuntu-20.x86_64.yml 示例：

```yaml
is_debian_based: true
is_ubuntu_based: true
is_ubuntu_x86: true

common_packages:
  - apt-transport-https
  - bash-completion
  - bridge-utils
  - ceph-common
  - chntpw
  - conntrack
  - conntrackd
  - curl
  - dkms
  - docker-ce         
  - git
  - glusterfs-common
  - gnupg-agent
  - gnupg2
  - ipset
  - ipvsadm
  - jq
  - kubeadm=1.15.12-00 
  - kubectl=1.15.12-00 
  - kubelet=1.15.12-00 
  - libusb-1.0-0
  - libusbredirparser1
  - librbd1
  - libspice-server1
  - nfs-common
  - ntp
  - openvswitch-switch
  - ovmf
  - parallel
  - python-selinux
  - software-properties-common
  - usbutils
  - wget
  - "{{ yunion_qemu_package }}"

common_services:
    - ntp
    - yunion-executor

latest_packages:
    - ca-certificates
    - yunion-climc
    - yunion-executor
    - yunion-fetcherfs
    - yunion-ocadm
```

该文件定义 Ubuntu 22.04 LTS x86_64 设置变量：

- `is_debian_based`: true
- `is_ubuntu_based`: true
- `is_ubuntu_x86`: true

ocboot 中一般在 `when`语句中根据操作系统变量中的定义进行条件过滤，所以对于 Debian 和 Ubuntu 中相同的操作，例如 `make cache for debian like os`这个 task，不需要对 `when`语句进行更改。

```yaml
- name: make cache for debian like os
  shell: "apt-get update"
  args:
    warn: no
  when:
  - is_debian_based is defined
```

而对于 `init apt cache for debian`等 task，Debian 和 Ubuntu 操作并不相同，需要修改对应的 `when` 语句或者修改相应 task 内容，将 is_debian_based 只抽象为 debian-based 操作系统共同的内容。

```yaml
- name: init apt cache for debian
  get_url:
    url: https://iso.yunion.cn/uos/buster/{{ debian_based_arch }}/3.8/yunion.gpg-key.asc
    dest: /tmp/yunion.gpg-key.asc
    validate_certs: no
  become: yes
  when:
  - is_debian_based is defined

- name: apply debian sig key
  shell: |
    apt-key add /tmp/yunion.gpg-key.asc;
    apt-get update -y;
    rm -f /tmp/yunion.gpg-key.asc
  args:
    executable: /bin/bash
  when:
  - is_debian_based is defined
```

2. common

可以新建 `onecloud/roles/common/tasks/ubuntu_22_x86_64.yml` 与 `onecloud/roles/common/tasks/ubuntu_22_aarch64.yml` 两个文件，文件内容可以参照 Debian 10。此外，Cloudpods [组件概览文档](https://www.cloudpods.org/zh/docs/setup/intro/)详细的描述了需要安装的组件。
以下为示例：

```yaml
---
# TODO: add ubuntu iso.yunion repo
- name: set var
  set_fact:
    onecloud_version_abbr: "{{ onecloud_version | regex_replace('[^0-9.]+') | regex_findall('^[0-9]+\\.[0-9]+') | join('')}}"

- name: config iptables for ubuntu 
  shell: |
    if iptables -V |grep -wq nf_tables && ls -l /usr/sbin/iptables |grep -wq alternatives; then
      update-alternatives --set iptables /usr/sbin/iptables-legacy
      update-alternatives --set ip6tables /usr/sbin/ip6tables-legacy
      update-alternatives --set arptables /usr/sbin/arptables-legacy
      update-alternatives --set ebtables /usr/sbin/ebtables-legacy
      if [ -x /usr/bin/aptitude ] && [ ! -x /usr/sbin/nft ]; then
          aptitude install nftables -y
          nft flush ruleset
      fi
    fi
  args:
    executable: /bin/bash

- name: init apt cache for ubuntu 
  get_url:
    url: https://iso.yunion.cn/ubuntu/{{ ansible_distribution_major_version }}/{{ onecloud_version_abbr }}/{{ ansible_architecture }}/yunion.gpg-key.asc
    dest: /tmp/yunion.gpg-key.asc
    validate_certs: no

- name: apply ubuntu sig key
  shell: |
    echo "deb [trusted=yes] https://iso.yunion.cn/ubuntu/{{ ansible_distribution_major_version }}/{{ onecloud_version_abbr }}/{{ ansible_architecture }}/ ./" > /etc/apt/sources.list.d/yunion.list;
    apt-key add /tmp/yunion.gpg-key.asc;
    apt-get update -y;
    rm -f /tmp/yunion.gpg-key.asc
  args:
    executable: /bin/bash

- name: install common packages via loop
...

- name: install latest packages via loop
...

- name: Check that if selinux config exists
...

- name: Turn off selinux
...
```

3. MariaDB

可以参照 Debian 10 相应架构内容，以 Ubuntu 22.04 LTS x86_64 安装 MariaDB 为例：

```yaml
- name: Install mariadb
  package:
    name: "{{ item }}"
    state: "present"
  with_items:
    - mariadb-server

- name: pips for mysql/mariadb
  pip:
    name: PyMySQL
  vars:
    ansible_python_interpreter: /usr/bin/python3

- name: Allow remote hosts to connect (Ubuntu)
  lineinfile:
    path: /etc/mysql/mariadb.conf.d/50-server.cnf
    backrefs: yes
    regexp: '^bind-address'
    line: 'bind-address            = 0.0.0.0'
    state: present

- name: make conf dir
  file:
    name: /etc/my.cnf.d
    state: directory

# restart the mariadb service asap to allow remote access
- name: Restart Mariadb
  systemd:
    name: mariadb
    state: restarted
    enabled: yes

- name: set fact for socket
  set_fact:
    login_unix_socket: /var/run/mysqld/mysqld.sock
```

5. 其他一些修改

包括改动后一些文档的更新，例如 [README.md](https://github.com/yunionio/ocboot/blob/master/README.md)、Cloudpods [安装相关文档](https://github.com/yunionio/docs)等内容。


## Ref

参考了以下 PR：
UOS：
- [兼容 uos x86 开源部署 by zhasm · Pull Request #64 · yunionio/ocboot](https://github.com/yunionio/ocboot/pull/64)

Debian
- [Feature/rex 3.9 add debian 10 support by zhasm · Pull Request #507 · yunionio/ocboot](https://github.com/yunionio/ocboot/pull/507)
- [feat: support debian x86_64 by zexi · Pull Request #68 · yunionio/ocboot](https://github.com/yunionio/ocboot/pull/68)

CentOS
- [feat(deploy,arch,arm64,centos7): add support for centos arm64 since 3.7 by zhasm · Pull Request #255 · yunionio/ocboot](https://github.com/yunionio/ocboot/pull/255/files)
- [fix(clickhouse): clickhouse deploy: only for centos x86 ISO by zhasm · Pull Request #622 · yunionio/ocboot](https://github.com/yunionio/ocboot/pull/622)

OpenEuler
- [兼容欧拉2022 LTS Sp1 by zhasm · Pull Request #773 · yunionio/ocboot](https://github.com/yunionio/ocboot/pull/773)
- [[wip]fix(euler,clickhouse): 欧拉支持clickhouse by zhasm · Pull Request #774 · yunionio/ocboot](https://github.com/yunionio/ocboot/pull/774)

Kylin
- [feat(kylin,deploy): add support for kylin x86, since 3.9 by zhasm · Pull Request #406 · yunionio/ocboot](https://github.com/yunionio/ocboot/pull/406)
- [fix(kylin,ha,mariadb): 麒麟环境下的高可用数据库部署bugfix by zhasm · Pull Request #536 · yunionio/ocboot](https://github.com/yunionio/ocboot/pull/536)
