### ISSUE TITLE
[BUG] 在Centos 7通过ocboot部署高可用报错：The error was: 'onecloud_version' is undefined

### ISSUE THREAD

**Issue by chenjacken** [yunionio/cloudpods#18357]
1，版本：
操作系统版本：
```
[root@master1 ocboot]# cat /etc/os-release 
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```
cloudpod版本：v3.10.6

2，进行高可用部署:
`./ocboot.py install ./config-k8s-ha.yml`，报错：

```
TASK [utils/kernel-check : Define kernel regex] ********************************
ok: [172.16.1.10]
ok: [172.16.1.9]

TASK [utils/kernel-check : test if nbd is supported] ***************************
changed: [172.16.1.10]
changed: [172.16.1.9]

TASK [utils/kernel-check : nbd facts] ******************************************
skipping: [172.16.1.10]
skipping: [172.16.1.9]

TASK [utils/kernel-check : Is Cloud kernel running] ****************************
ok: [172.16.1.10]
ok: [172.16.1.9]

TASK [utils/kernel-check : Is cloud kernel installed] **************************
ok: [172.16.1.10]
ok: [172.16.1.9]

TASK [utils/kernel-check : install customized kernel] **************************
included: /opt/ocboot/onecloud/roles/utils/kernel-check/tasks/centos-x86_64.yml for 172.16.1.10, 172.16.1.9

TASK [utils/kernel-check : version test] ***************************************
fatal: [172.16.1.10]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'onecloud_version' is undefined\n\nThe error appears to be in '/opt/ocboot/onecloud/roles/utils/kernel-check/tasks/centos-x86_64.yml': line 2, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n# This role contains common plays that will run on all nodes\n- name: version test\n  ^ here\n"}
fatal: [172.16.1.9]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'onecloud_version' is undefined\n\nThe error appears to be in '/opt/ocboot/onecloud/roles/utils/kernel-check/tasks/centos-x86_64.yml': line 2, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n# This role contains common plays that will run on all nodes\n- name: version test\n  ^ here\n"}

PLAY RECAP *********************************************************************
172.16.1.10                : ok=171  changed=30   unreachable=0    failed=1    skipped=61   rescued=0    ignored=0
172.16.1.8                 : ok=123  changed=18   unreachable=0    failed=0    skipped=33   rescued=0    ignored=0
172.16.1.9                 : ok=168  changed=29   unreachable=0    failed=1    skipped=60   rescued=0    ignored=0

[root@master1 ocboot]# 
```

**Comment by zexi** [comment]
@chenjacken 这个问题我昨天修复了，拉取最新的 ocboot release/3.10 代码再重新执行试试？

**Comment by zexi** [comment]
@chenjacken 麻烦把 ./config-k8s-ha.yml 里面的内容贴下

**Comment by chenjacken** [comment]
#18166 看过这个，还是有问题。

config-k8s-ha.yml内容，参考：https://www.cloudpods.org/zh/docs/setup/ha-ce/

```
primary_master_node:
  hostname: 172.16.1.8
  use_local: false
  user: root
  onecloud_version: "v3.10.6"
  db_host: 172.16.1.99
  db_user: "root"
  db_password: "hwyDB_@2024"
  db_port: "3306"
  skip_docker_config: true
  image_repository: registry.cn-guangzhou.aliyuncs.com/createview
  ha_using_local_registry: false
  node_ip: "172.16.1.8"
  ip_autodetection_method: "can-reach=172.16.1.8"
  controlplane_host: 172.16.1.100
  controlplane_port: "6443"
  as_host: true
  high_availability: true
  use_ee: false
  enable_minio: true
  registry_mirrors:
  - https://lje6zxpk.mirror.aliyuncs.com
  insecure_registries:
  - 172.16.1.8:5000
  host_networks: "eno1/br0/172.16.1.8"

master_nodes:
  controlplane_host: 172.16.1.100
  controlplane_port: "6443"
  as_controller: true
  as_host: true
  ntpd_server: "172.16.1.8"
  registry_mirrors:
  - https://lje6zxpk.mirror.aliyuncs.com
  high_availability: true
  hosts:
  - user: root
    hostname: "172.16.1.9"
    host_networks: "eno1/br0/172.16.1.9"
  - user: root
    hostname: "172.16.1.10"
    host_networks: "eno1/br0/172.16.1.10"
```
