### ISSUE TITLE
[求助/Help]容器下新建集群不成功，web显示：创建失败

### ISSUE THREAD

**Issue by chenjacken** [yunionio/cloudpods#18575]
<img width="1090" alt="image" src="https://github.com/yunionio/cloudpods/assets/935084/5cac596a-7625-4f30-bcfc-9346d684779a">

<img width="1077" alt="image" src="https://github.com/yunionio/cloudpods/assets/935084/418126ac-53dc-41e4-b527-15f0bba74443">

一，版本信息
cloudpods：v3.10.6，高可用部署，存储使用ceph
宿主机：Centos7

二，开启了k8s功能：`climc feature-config-k8s --switch on`，在web页面上，“容器”-“集群”-“新建集群”，我设置的1个控制节点的集群，等到几个状态改变后，显示：创建失败，具体情况如下：
1）我在虚拟机列表中，能查看到由该“新建集群”所创建的虚拟机，虚拟机是运行状态，进入虚拟机SSH
```
[root@kubernetes-controlplane-dhc4-0 ~]# kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.9", GitCommit:"6df4433e288edc9c40c2e344eb336f63fad45cd2", GitTreeState:"clean", BuildDate:"2022-04-13T19:57:43Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.9", GitCommit:"6df4433e288edc9c40c2e344eb336f63fad45cd2", GitTreeState:"clean", BuildDate:"2022-04-13T19:52:02Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
[root@kubernetes-controlplane-dhc4-0 ~]# 
```
2）在web页面查看“创建失败”的几条操作日志
```
{
    "__reason__": "Get \"https://172.16.1.197:6443/version?timeout=30s\": dial tcp 172.16.1.197:6443: connect: connection refused",
    "__stage__": "OnSyncStatus",
    "__status__": "ERROR"
}
```

```
{
    "__reason__": {
        "reason": "{\"__reason__\":\"Get \\\"https://172.16.1.197:6443/version?timeout=30s\\\": dial tcp 172.16.1.197:6443: connect: connection refused\",\"__stage__\":\"OnSyncStatus\",\"__status__\":\"ERROR\"}",
        "stage": "OnSyncStatus"
    },
    "__stage__": "OnSyncStatusComplete",
    "__status__": "error",
    "__task_name__": "ClusterSyncstatusTask"
}
```

```
{
    "__reason__": {
        "reason": "{\"__reason__\":{\"reason\":{\"__reason__\":{\"reason\":\"{\\\"__reason__\\\":\\\"Get \\\\\\\"https://172.16.1.197:6443/version?timeout=30s\\\\\\\": dial tcp 172.16.1.197:6443: connect: connection refused\\\",\\\"__stage__\\\":\\\"OnSyncStatus\\\",\\\"__status__\\\":\\\"ERROR\\\"}\",\"stage\":\"OnSyncStatus\"},\"__stage__\":\"OnSyncStatusComplete\",\"__status__\":\"error\",\"__task_name__\":\"ClusterSyncstatusTask\"},\"stage\":\"OnSyncStatusComplete\"},\"__stage__\":\"OnMachinesDeployed\",\"__status__\":\"error\",\"__task_name__\":\"ClusterDeployMachinesTask\"}",
        "stage": "OnMachinesDeployed"
    },
    "__stage__": "OnMachinesCreated",
    "__status__": "error",
    "__task_name__": "ClusterCreateMachinesTask"
}
```

```
{
    "__reason__": "add cluster to client manager: clusterId kubernetes current status create_fail: Cluster not running",
    "__stage__": "OnSyncComplete",
    "__status__": "ERROR"
}
```
3），在web页面查看“创建失败”的集群的kubeconfig，是已经同步kubeconfig的信息
<img width="840" alt="image" src="https://github.com/yunionio/cloudpods/assets/935084/216c391b-2138-4041-b4e1-79dbd0722f87">

```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMvakNDQWVhZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJek1URXdOVEl3TWpNeU4xb1hEVE16TVRFd01qSXdNak15TjFvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTjRrCmdPZHFRSDh6WkZ4Q200TTBBUjkxa2FtcGx2ZWg1STQwbGE1UTBEczNsYklsYzZ0cVhJYmc3akQ0UUhiUmJXZUoKWWxKd0h0TUJOaHNORXBZTlFLSXZlcUJnQkJ2d3JjTHVTUnc5dzZBVzd6dFB1UTc5ZmtuUjJTdzg1d0RSd01pNwovQ2lOMTdCYzdqbWRERGhjSCtpTXozRHEwNGFVbmlwek1Pa0tFTTdOSnBpczBHWjlmbHp2VFVUWVNTaFNxbWJtCm5JbjYvTTdLNEdtZElsWVZHYTNZdnZyQ1puZ1d3aS9yVm1rYmJzWHVHSGRkSytYYmhRTlJldkpwWWN0TUpHTk0Ka21iV1kyeVJucU1rS1R0NVg2SWRwcitKK00wMmh3Uy81RXhTQ0tob0d5QUJlbzUxc1hjYk1rZGliTjBwNE9CaAoybWI5OUUrMDd4WC84R1B0ZHNFQ0F3RUFBYU5aTUZjd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZKVjgvMkhna1VjWWhCWDlaYnpjdnZCUW5TdWJNQlVHQTFVZEVRUU8KTUF5Q0NtdDFZbVZ5Ym1WMFpYTXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBTDVKcXZFTDcrWjYzQkNNTmtnOAo3OWJsaU1DV3hNbWxRS21zQkJId1Q5RDFpa0lqbEttT3hWV2V0ZG1QVnFLTURvUTloM2dtc2JqRnd3b1NIdUxVClFOa3pqL0pRUFdPVzdLaHZRanREYXdYYnNzRUJmR1BzcDRlMkM5MXo3bGNZZGpERVV6MVNwS1J6TExCcWIzZDgKLzF4a2xlR0lETDNPdVdGSk5XNWpzckNtT2tWOTBKUEM1V0lzbnZwTC9YNUQ1WmJPMlVMUFRCWEVSb2tkWmNNVApveGRxOHdYUXM0a1gvdnFUZTZPOElSQWwvQXhEWFNnMjllWlhEeG9vYjBMZkg4bzkyeGFqUVQ4em9tMGo0SmhlCmk2RHQ0NFV5ZGt1cnhXdno0YUYyd05qUnZVNU5OOWhscDdTMUUxRTc1MktGUzVuS0xWdzdXeHhPYVZWbys4WWkKcFY4PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://172.16.1.197:6443
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: kubernetes-admin
  name: kubernetes-admin@kubernetes
current-context: kubernetes-admin@kubernetes
kind: Config
preferences: {}
users:
- name: kubernetes-admin
  user:
    client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURGVENDQWYyZ0F3SUJBZ0lJTVpGbmdDYVB5UG93RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWdGdzB5TXpFeE1EVXlNREl6TWpkYUdBOHlNVEl6TVRBeE1qSXdNall4TmxvdwpOREVYTUJVR0ExVUVDaE1PYzNsemRHVnRPbTFoYzNSbGNuTXhHVEFYQmdOVkJBTVRFR3QxWW1WeWJtVjBaWE10CllXUnRhVzR3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRQzlIYWJqc1NjTCtTQkQKRUlCaXlab3ZnYURLWFZ0SDgxdDJEUkoycmkvaEU4OCtqRVMrLy94SUs5ck5vWWlSYk4zWkNHdGNoZ1BsRzBoUApGVHdvRWF2WUNBL1ZPWHMrZ1VEZjZmVWFEZCtWWlBCVnZlNG1EYmRaNDVKemF0RkVHckVLWGp6aUhwcHhHZEJRCjJpa3FVWUZXRUE4RUZIcElwSXhwQnpPZW9vc1NsVlVnb0Y3NDVHNktpU2RhVC9Qb2FGNm5HL2xGVkp3TjBPM3cKTG1rNjVja1Z5QzA1aVZoc2dSd2d5bGFBb3JnSDkrSktvU2NsWTFyS0N4SVlONXFzYVMweldCSUEzOTRRazliUwpKZFVLK2szZHlNQUkweHQ1Q2liQWJZb05Bc0cyNFVNVVljU25uWk5Zei9VQWJEY3haaFZXSFJIbjhnK2FmRXlNCmt2TUtNUGQ5QWdNQkFBR2pTREJHTUE0R0ExVWREd0VCL3dRRUF3SUZvREFUQmdOVkhTVUVEREFLQmdnckJnRUYKQlFjREFqQWZCZ05WSFNNRUdEQVdnQlNWZlA5aDRKRkhHSVFWL1dXODNMN3dVSjBybXpBTkJna3Foa2lHOXcwQgpBUXNGQUFPQ0FRRUFFazAxWDFDblR1ekg1TlFlMFZGd3NjYW9KL0lNcXVCWDMwNmZuN2V3dzE3c1BTN3VZbUh5CkhCemNZKzFSWTJXdGxMRW5jUlZBYlk4TG1nNFJSa2drSk1MSktidUVmTjcxQU9Kc29ubkYvZWZhay9PaHc1TTUKbEUyMzUyYVF0VWlzRjZ5MW1LNVowaE5EdVJwUXVJb0t0SjdBZzJhRXdFZkdjZEI1U0NnQVl6bXBFdVlMZWtFUwowdHd3VUV4VUhSMHNJalp1SVkxNlNQeW5wR1dweWJqU3IrUVVjRVkrRmpIR2hxZFZpSEJnYUk0VVpKYVN5cW1OCk9OYVFGbU84YUpYY0U5OVhSbHAyZ3Awb2dqK1RDaFV6Nm54Qzd5dWpuVFZwank0SHk2Z3JZazhab0Z4WmVuN2IKbmJDeTRCa2ZRR3ZyQVY3RkVCelJja0F2cHdTemEyMys0UT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    client-key-data: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcFFJQkFBS0NBUUVBdlIybTQ3RW5DL2tnUXhDQVlzbWFMNEdneWwxYlIvTmJkZzBTZHE0djRSUFBQb3hFCnZ2LzhTQ3ZhemFHSWtXemQyUWhyWElZRDVSdElUeFU4S0JHcjJBZ1AxVGw3UG9GQTMrbjFHZzNmbFdUd1ZiM3UKSmcyM1dlT1NjMnJSUkJxeENsNDg0aDZhY1JuUVVOb3BLbEdCVmhBUEJCUjZTS1NNYVFjem5xS0xFcFZWSUtCZQorT1J1aW9rbldrL3o2R2hlcHh2NVJWU2NEZER0OEM1cE91WEpGY2d0T1lsWWJJRWNJTXBXZ0tLNEIvZmlTcUVuCkpXTmF5Z3NTR0RlYXJHa3RNMWdTQU4vZUVKUFcwaVhWQ3ZwTjNjakFDTk1iZVFvbXdHMktEUUxCdHVGREZHSEUKcDUyVFdNLzFBR3czTVdZVlZoMFI1L0lQbW54TWpKTHpDakQzZlFJREFRQUJBb0lCQUQ3R0t2R0Zpa3FGSlZwZApqZUE4dnp0cHNlKzZVV1J1dVR0VVYzNmhqeThOSGt2S3o3Nyt4Y1ZIR1ZnTWVJS2RPbjZpTnREOWd5bDNodWNKClMzQ1pmUXMya2RyYk83ZWh1K0VYamM1YU1JOHNkRUpoeXoxQ2JFd2dLQ3E3bUQ4ZEJRdEdBTHVtSU9uT0FjSDAKeUpsTmVMc1NsWWxyS3JRV09xMWFRSjQxb2loR2EwUjdjU1RhMlhHMm9PaksyTU9IZXZHL2NSdWFacVlyRXZvdgo5SWdmV3I4d1U4cWZHQjBiTHIwY2xlVTF2U0lVOXFtYVIvU0FxazNwYWpUTUlvNFpaekpvUUFnZ0pJQ01OcS80CllJY3Z5MWhiMTNycC93TnJkVURLUEVlL2M3YmpSTUs5MnBrVTE1dGlZdUQ5cnBDS0hSYXVkdlNab1YwOTZoVFcKU1VhbVZNRUNnWUVBMGxYdTJTMVZPbEVCSWNmREllem85ZWUxUUw1MyszbTJsR0pNQjdJT1NweWZGRU9iaUdKWQp2RThOR2NJdkpJNk1WajFoSzR1N0dzaThKWFkxbXRPeGZxa1ptR0VoQnVUUFI5Z3BpbTR1akYxTnNrdUllS05sCkVuODhzeFgvNlVlSllxamsvc2pVOGZrV255d3ZYREg4NTFQZitQUVJ5M2VaQWJDTEdvTzdYemtDZ1lFQTVpeGIKN1UxMFFIcjExVHlOZ2d6Uk51Slk5enpZNGRBM2hWYjJ6VHZoZG9rSTNZVjJ5RzlxM1hOU05TcjB6c05xZEthQgpMcllDdkc3QTZFYTFRYVp5QUJJVGhGUVRVN2IvYmtoeEVodWdpYVk5Nk1kM0dLTjcrajZibkFmNzBJWGJCZGVDCmpBZ1NnRis1V3crMDBydm00NnhLY2xSWHdpTWh0N1JHTU9wQmxtVUNnWUVBblA3QlFkOWhieDdKWG9KeGR1QVQKWG9DdHZINnVwY2pLYStVVzVPT1ZZVUdZUjVMVEE3Q01sVG5ZQ0hMMXB5NnpOeWVuWU01eVFPSzE5S3hRQkptZwpNVzljaUcxdkxtc1pBSUlyTjRWWVB6TGhiSVNPZjZWT0tzbEg4RkFxYk9BVmZzdWI2VVRVRlN5Y0l3RGk5TWpuCkFXK01qSkQ0dTBzd3JKOHVwUUxRbDVrQ2dZRUF4QlRLQXpCV2RvL0pXT3lLeUYxTzVXaVJ6WjFDVGF4cGYrZ0QKdS9ibExXdXo1N0xJN0JzdWVKVERWWlBRbFV1WUp1T3BiVGVVd1IzQXJKOS96ZnVUWmtmLzVGMFRVZCsxWGlmTQpXMWE1dmttbXQrVWtxaEtyalJWRXp2bG1KYy9DTkFuUnBxVkJ6YWErYXJySW1qV0Vqak82QUFlbDh6YW1oSzdJCmxPY2JGSmtDZ1lFQXBBdklMYzF4QWV2VlpGTTZNM3NPNWZIbW5VaXRsN2Z3V1NvcmtFR3kxT2JrQzVZcDBSeXUKRFJnaHBQL3lJMWptRGpvUjV5M05pdk9nN3FkWnZnR1BHdDlqUTJPbTdNbHByQ0ljcmZHVklpTllhUHN1MkJUKwpQQUxNMkd4REoxOGFrR2JXZktzVVpocTRab3VBT1FsM0dQTGxyVUJwUmcrbFR5Z3JFNXVmTWJvPQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
```

4）在宿主机上访问`https://172.16.1.197:6443/version?timeout=30s`，也是能成功访问
```
[root@master1 ~]# curl -k https://172.16.1.197:6443/version?timeout=30s
{
  "major": "1",
  "minor": "22",
  "gitVersion": "v1.22.9",
  "gitCommit": "6df4433e288edc9c40c2e344eb336f63fad45cd2",
  "gitTreeState": "clean",
  "buildDate": "2022-04-13T19:52:02Z",
  "goVersion": "go1.16.15",
  "compiler": "gc",
  "platform": "linux/amd64"
}[root@master1 ~]# 
```

三，同步以上的kubeconfig信息，通过web的导入集群方式，导入成功

<img width="1241" alt="image" src="https://github.com/yunionio/cloudpods/assets/935084/f55d8902-7e28-4cc5-8e7d-7e9dfe34101a">

**四，猜测的问题点**

创建集群时候，同步进行创建虚拟机，并同步部署k8s服务，可能是创建虚拟机-部署k8s等速度比较慢，还未创建起来，而容器管理服务检查部署情况时出现超时等情况，从而标记该集群创建失败。实时上，该集群对应的虚拟机是已经创建k8s成功了的。
是有配置入口修改这些部署状态检测点的超时时间等？
