### ISSUE TITLE
[求助/Help]宿主机频繁卡死，服务掉线，无法使用该宿主机，整个集群感觉无法使用

### ISSUE THREAD

**Issue by chenjacken** [yunionio/cloudpods#19748]
一，版本：
1，v3.11.0版本，部署了高可用版本
2，操作系统是centos7
3，内核：5.4.130-1.yn20230805.el7.x86_64
4，宿主机开启了大内存页，预留内存：18G
5，ceph，使用rook+ceph部署方式， https://www.cloudpods.org/blog/rook-ceph-with-cloudpods ，使用了`使用 Pacific (v16) Ceph`

二，集群内的宿主机几台服务器，会不定时频繁卡死，卡死的情况：
1，无法SSH进入
2，web提示该宿主机警告：`system.uptime`
3，所在的宿主机CEPH的OSD掉线down了
4，该宿主机所在的虚拟机也不能使用

三，监控一些进程情况，主要是qemu进程挤爆CPU，ceph-osd占用内容也很猛

CPU:
<img width="1102" alt="image" src="https://github.com/yunionio/cloudpods/assets/935084/5b3f1d92-c170-4f8f-8798-4be5b549cb68">

![WechatIMG7424](https://github.com/yunionio/cloudpods/assets/935084/ee49894d-7faa-4726-a2dd-fa5dc36b0ab2)

这个问题经常发生，感觉整个集群不能正常持续使用，麻烦帮忙指导排查解决，谢谢。

**Comment by wanyaoqi** [comment]
@chenjacken top 看宿主机 load 太高了，需要找一下瓶颈，IO还是内存
free  看下内存是否足够，CPU大部分时间都耗在 wait

<img width="656" alt="image" src="https://github.com/yunionio/cloudpods/assets/18528551/f681d30d-510e-41d5-b670-eab571f077b1">

**Comment by chenjacken** [comment]
> @chenjacken top 看宿主机 load 太高了，需要找一下瓶颈，IO还是内存 free 看下内存是否足够，CPU大部分时间都耗在 wait
> 
> <img alt="image" width="656" src="https://private-user-images.githubusercontent.com/18528551/314360212-f681d30d-510e-41d5-b670-eab571f077b1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA5MDM0NzYsIm5iZiI6MTcxMDkwMzE3NiwicGF0aCI6Ii8xODUyODU1MS8zMTQzNjAyMTItZjY4MWQzMGQtNTEwZS00MWQ1LWI2NzAtZWFiNTcxZjA3N2IxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIwVDAyNTI1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5YjQwOTg1ZGUxZDcwM2VhYzU0MzU4YTU3Y2M2ZTUzOGJmZWQ5NzNiZGNjMDk1OGY2NTY2ZWQ2OTQzZjA5ODUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.K_fb7bX4930rK5wYgkMrN5X_SJvGVU-0cPBtyAsQBjs">



> @chenjacken top 看宿主机 load 太高了，需要找一下瓶颈，IO还是内存 free 看下内存是否足够，CPU大部分时间都耗在 wait
> 
> <img alt="image" width="656" src="https://private-user-images.githubusercontent.com/18528551/314360212-f681d30d-510e-41d5-b670-eab571f077b1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA5MDM0NzYsIm5iZiI6MTcxMDkwMzE3NiwicGF0aCI6Ii8xODUyODU1MS8zMTQzNjAyMTItZjY4MWQzMGQtNTEwZS00MWQ1LWI2NzAtZWFiNTcxZjA3N2IxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIwVDAyNTI1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5YjQwOTg1ZGUxZDcwM2VhYzU0MzU4YTU3Y2M2ZTUzOGJmZWQ5NzNiZGNjMDk1OGY2NTY2ZWQ2OTQzZjA5ODUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.K_fb7bX4930rK5wYgkMrN5X_SJvGVU-0cPBtyAsQBjs">


这个是内存的截图：
<img width="1071" alt="image" src="https://github.com/yunionio/cloudpods/assets/935084/6957b868-eec7-46b9-b1ee-5ed9ca5425e8">

**Comment by chenjacken** [comment]
ROOK-CEPH的配置cluster.yaml重要信息：
```
  resources:
# The requests and limits set here, allow the mgr/mon/osd pod to use half of one CPU core and 1 gigabyte of memory
    mon:
      limits:
        cpu: "4000m"
        memory: "8Gi"
      requests:
        cpu: "4000m"
        memory: "8Gi"
    mgr:
      limits:
        cpu: "4000m"
        memory: "4Gi"
      requests:
        cpu: "4000m"
        memory: "4Gi"
    osd:
      limits:
        cpu: "4000m"
        memory: "8Gi"
      requests:
        cpu: "4000m"
        memory: "8Gi"

  storage: # cluster level storage configuration and selection
    useAllNodes: false
    useAllDevices: false
    #deviceFilter:
    config:
      # crushRoot: "custom-root" # specify a non-default root label for the CRUSH map
      # metadataDevice: "md0" # specify a non-rotational storage so ceph-volume will use it as block db device of bluestore.
      # databaseSizeMB: "1024" # uncomment if the disks are smaller than 100 GB
      # journalSizeMB: "1024"  # uncomment if the disks are 20 GB or smaller
      # osdsPerDevice: "1" # this value can be overridden at the node or device level
      # encryptedDevice: "true" # the default value for this option is "false"
# Individual nodes and their config can be specified as well, but 'useAllNodes' above must be set to false. Then, only the named
# nodes below will be used as storage resources.  Each node's 'name' field should match their 'kubernetes.io/hostname' label.
    nodes:
    - name: "master1"
      devices:
      - name: "nvme0n1"
      - name: "sdc"
    - name: "master2"
      devices:
      - name: "nvme0n1"
      - name: "sdc"
    - name: "master3"
      devices:
      - name: "nvme0n1"
      - name: "sdc"
    - name: "node1"
      devices:
      - name: "sdc"
    - name: "node2"
      devices:
      - name: "nvme0n1"
      - name: "sdc"

```

++++++++++++++++++++++++++

rook-config-override的内容：
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: rook-config-override
  namespace: rook-ceph
data:
  config: |
    [global]
    public network =  172.16.1.0/24
    cluster network = 10.0.1.0/24
    public addr = ""
    cluster addr = ""
    osd pool default size = 3
    osd pool default min size = 1
    mon allow pool delete = true
    osd pool default pg num = 128
    osd pool default pgp num = 128
    mon max pg per osd = 900
    mon osd full ratio = 0.95
    mon osd nearfull ratio = 0.85
    max open files = 131072
    
    [mon]
    mon clock drift allowed = 1
    mon osd min down reporters = 3
    mon osd down out interval = 600

    [osd]
    osd journal size = 20000
    osd mkfs type = xfs
    osd max write size = 512
    osd client message size cap = 2147483648
    osd deep scrub stride = 131072
    osd op threads = 16
    osd disk threads = 4
    osd map cache size = 1024
    osd map cache bl size = 128
    osd mount options xfs = "rw,noexec,nodev,noatime,nodiratime,nobarrier"
    osd recovery op priority = 2
    osd recovery max active = 10
    osd recovery thread timeout = 120
    osd recovery thread suicide timeout = 2000
    osd max backfills = 4
    osd min pg log entries = 30000
    osd max pg log entries = 100000
    osd mon heartbeat interval = 40
    osd op thread timeout = 90
    osd op thread suicide timeout = 2000
    ms dispatch throttle bytes = 1048576000
    objecter inflight ops = 819200
    osd op log threshold = 50
    osd crush chooseleaf type = 0
    filestore xattr use omap = true
    filestore min sync interval = 10
    filestore max sync interval = 15
    filestore queue max ops = 25000
    filestore queue max bytes = 1048576000
    filestore queue committing max ops = 50000
    filestore queue committing max bytes = 10485760000
    filestore split multiple = 8
    filestore merge threshold = 40
    filestore fd cache size = 1024
    filestore op threads = 32
    filestore op thread timeout = 180
    filestore op thread suicide timeout = 2000
    journal max write bytes = 1073714824
    journal max write entries = 10000
    journal queue max ops = 50000
    journal queue max bytes = 10485760000
    
    [client]
    rbd cache = true
    rbd cache size = 335544320
    rbd cache max dirty = 134217728
    rbd cache max dirty age = 30
    rbd cache writethrough until flush = false
    rbd cache max dirty object = 2
    rbd cache target dirty = 235544320
```

请问有比较优的配置方案？
