### ISSUE TITLE
[求助/Help] 在云联系统里面，申请了两台云主机，用来测试HA。失败。

### ISSUE THREAD

**Issue by lonso** [yunionio/cloudpods#19849]
![image](https://github.com/yunionio/cloudpods/assets/5660818/d18c8115-fed5-4f56-9431-df0e50e73b46)

A:  10.0.105.152
B: 10.0.105.142
VIP: 10.0.105.251

现在会卡在 TASK [utils/kernel-check : Reboot system if not cloud kernel, it should take a few minutes...]。然后就超时。

**Comment by zhasm** [comment]
@lonso 
ocboot 代码已经更新，更新了重启逻辑。请拉取最新代码试试？

**Comment by lonso** [comment]
我们目前用的3.10的。所以需要在3.10上测试😂

**Comment by zhasm** [comment]
3.10 的ocboot 也已经更新了~
另外，HA 建议 3 台以上的节点~（2 台不建议）

**Comment by lonso** [comment]
好的。我在试试

**Comment by lonso** [comment]
```yaml
primary_master_node:
  # ssh login IP
  hostname: 10.0.105.152
  # 不使用本地登录方式
  use_local: false
  # ssh login user
  user: root
  # cloudpods version
  onecloud_version: "v3.10.0"
  # mariadb connection address
  db_host: "10.0.105.141"
  # mariadb user
  db_user: "root"
  # mariadb password
  db_password: "qwer1234"
  # mariadb port
  db_port: "3306"
  # 节点服务监听的地址，多网卡时可以指定对应网卡的地址
  node_ip: "10.0.105.152"
  # 对应 Kubernetes calico 插件默认网卡选择规则
  ip_autodetection_method: "can-reach=10.0.105.152"
  # K8s 控制节点的 IP，对应keepalived 监听的 VIP
  controlplane_host: 10.0.105.251
  # K8s 控制节点 apiserver 监听的端口
  controlplane_port: "6443"
  # 该节点作为 Cloudpods 私有云计算节点，如果不想让控制节点作为计算节点，可以设置为 false
  as_host: true
  # 虚拟机可作为 Cloudpods 内置私有云计算节点（默认为 false）。开启此项时，请确保 as_host: true
  as_host_on_vm: true
  # 产品版本，从 [Edge, CMP, FullStack] 选择一个，FullStack 会安装融合云，CMP 安装多云管理版本，Edge 安装私有云
  product_version: 'Edge'
  # 服务对应的镜像仓库，如果待部署的机器不在中国大陆，可以用 dockerhub 的镜像仓库：docker.io/yunion
  image_repository: registry.cn-beijing.aliyuncs.com/yunion
  # 启用高可用模式
  high_availability: true
  # 使用 minio 作为后端虚拟机镜像存储
  enable_minio: true
    #  insecure_registries:
    # - registry.paralinker.com
  ha_using_local_registry: false
  # 计算节点默认网桥 br0 对应的网卡
  host_networks: "eth0/br0/10.0.105.152"

master_nodes:
  # 加入控制节点的 k8s vip
  controlplane_host: 10.0.105.251
  # 加入控制节点的 K8s apiserver 端口
  controlplane_port: "6443"
  # 作为 K8s 和 Cloudpods 控制节点
  as_controller: true
  # 该节点作为 Cloudpods 私有云计算节点，如果不想让控制节点作为计算节点，可以设置为 false
  as_host: true
  # 虚拟机可作为 Cloudpods 内置私有云计算节点（默认为 false）。开启此项时，请确保 as_host: true
  as_host_on_vm: true
  # 从 primary 节点同步 ntp 时间
  ntpd_server: "10.0.105.152"
  # 启用高可用模式
  high_availability: true
  # insecure_registries:
    #- registry.paralinker.com
  hosts:
  - user: root
    hostname: "10.0.105.142"
    # 计算节点默认网桥 br0 对应的网卡
    host_networks: "eth0/br0/10.0.105.142"
  - user: root
    hostname: "10.0.105.115"
    host_networks: "eth0/br0/10.0.105.115"
```

现在更新代码以后。提示 TASK [master-node : Use ocadm join master node]  这个了。
