### ISSUE TITLE
[求助/Help]Docker Compose方式安装失败--read config options error

### ISSUE THREAD

**Issue by youngperson** [yunionio/cloudpods#21953]
**报错信息**
docker-compose.yml放在/data目录下，进入该目录后执行docker compose up

[root@iv-ydjq3bnksg6dqxo22av2 data]# pwd
/data
[root@iv-ydjq3bnksg6dqxo22av2 data]# docker compose up

WARN[0000] Found orphan containers ([data-host-deployer-init-1 data-host-deployer-1 data-esxi-agent-init-1 data-cloudid-init-1 data-esxi-agent-1 data-cloudid-1 data-esxi-agent-post-init-1 data-cloudid-post-init-1]) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up. 

data-web-init-1                 | [fatal 250110 07:49:11 main.main(main.go:69)] construct cluster error: construct cluster: read config options from "/etc/yunion/keystone.conf": read content of "/etc/yunion/keystone.conf": read /etc/yunion/keystone.conf: is a directory

data-keystone-init-1            | [fatal 250110 07:49:17 main.main(main.go:69)] construct cluster error: construct cluster: read config options from "/etc/yunion/monitor.conf": read content of "/etc/yunion/monitor.conf": read /etc/yunion/monitor.conf: is a directory

**疑问**
1、xxx.conf配置文件在哪获取到，需要提前放置到宿主机上？
2、打包镜像的时候需要把xxx.conf配置文件放进去？

**需求：**
在一台服务上使用Compose的方式进行部署cloudpods
cloudpodweb、keystone、region、apigateway的镜像有做过修改

**机器信息：**
- Linux iv-ydjq3bnksg6dqxo22av2 5.14.0-312.el9.x86_64  1 SMP PREEMPT_DYNAMIC Thu May 11 16:26:43 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
- 8c 16g，系统盘是40GB，数据盘是100GB

**打包的方式是**  
```
 # 项目地址 https://github.com/yunionio/cloudpods/tree/release/3.10
cd /data/code/cloudpods   

 # 后端项目打包上传到镜像仓库
VERSION=1.0 ARCH=amd64 REGISTRY=crpi-5xevxsf5bgb3t0ps.cn-hongkong.personal.cr.aliyuncs.com/yunionio1021 make image keystone region apigateway 

# 项目地址 https://github.com/yunionio/dashboard/tree/release/3.10
cd /data/code/dashboard  

# 前端项目打包上传到镜像仓库
REGISTRY=crpi-5xevxsf5bgb3t0ps.cn-hongkong.personal.cr.aliyuncs.com/yunionio1021 TAG=cluodpodsWeb1.0 ./scripts/docker_push.sh   
```

**准备好的docker-compose.yml**
```
version: '3.9'
services:
  mysql:
    image: registry.cn-beijing.aliyuncs.com/yunionio/mariadb:10.5.19
    ports:
    - 3307:3306
    volumes:
    - ./data/var/lib/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: your-sql-password
      MYSQL_TCP_PORT: '3306'
      MYSQL_ROOT_HOST: '%'
      MARIADB_AUTO_UPGRADE: 'true'
      MARIADB_DISABLE_UPGRADE_BACKUP: 'true'
    healthcheck:
      test: mysqladmin ping -h mysql -P 3306 -p$$MYSQL_ROOT_PASSWORD
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 30s
  etcd:
    image: registry.cn-beijing.aliyuncs.com/yunionio/etcd:3.4.6
    volumes:
    - ./data/etc/yunion/pki/:/etc/yunion/pki/:ro
    environment:
      ETCDCTL_API: '3'
    command:
    - /usr/local/bin/etcd
    - --data-dir=/var/etcd/data
    - --name=etcd
    - --initial-advertise-peer-urls=http://etcd:2380
    - --listen-peer-urls=http://0.0.0.0:2380
    - --listen-client-urls=http://0.0.0.0:2379
    - --advertise-client-urls=http://etcd:2379
    - --initial-cluster=etcd=http://etcd:2380
    - --initial-cluster-state=new
    - --quota-backend-bytes
    - '134217728'
    - --auto-compaction-retention
    - '1'
    - --max-wals
    - '1'
    - --initial-cluster-token=7f283eed-0f7f-4d55-9159-32e673517b53
    healthcheck:
      test: /bin/sh -ec ETCDCTL_API=3 etcdctl endpoint status
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 30s
    restart: on-failure
  keystone-init:
    image: registry.cn-beijing.aliyuncs.com/yunionio/compose-service-init:v3.10-lzx-0331.1
    volumes:
    - ./data/etc/yunion/:/etc/yunion/
    depends_on:
      mysql:
        condition: service_healthy
    command:
    - /opt/yunion/bin/compose-service-init
    - --config-dir=/
    - --component=keystone
    - --step=init
    - --mysql-host=mysql
    - --mysql-port=3306
    - --mysql-user=root
    - --mysql-password=your-sql-password
  keystone:
    image: crpi-5xevxsf5bgb3t0ps.cn-hongkong.personal.cr.aliyuncs.com/yunionio1021/keystone:1.0
    volumes:
    - ./data/etc/yunion/pki/:/etc/yunion/pki/:ro
    - ./data/etc/yunion/keystone.conf:/etc/yunion/keystone.conf:ro
    depends_on:
      keystone-init:
        condition: service_completed_successfully
      mysql:
        condition: service_started
      etcd:
        condition: service_healthy
    command:
    - /opt/yunion/bin/keystone
    - --config
    - /etc/yunion/keystone.conf
    - --auto-sync-table
    healthcheck:
      test: netstat -tln | grep -c 30500
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 30s
    restart: on-failure
  keystone-post-init:
    image: registry.cn-beijing.aliyuncs.com/yunionio/compose-service-init:v3.10-lzx-0331.1
    volumes:
    - ./data/etc/yunion/:/etc/yunion/
    depends_on:
      mysql:
        condition: service_healthy
      keystone:
        condition: service_healthy
    command:
    - /opt/yunion/bin/compose-service-init
    - --config-dir=/
    - --component=keystone
    - --step=post-init
    - --mysql-host=mysql
    - --mysql-port=3306
    - --mysql-user=root
    - --mysql-password=your-sql-password
    restart: on-failure
  logger-init:
    image: registry.cn-beijing.aliyuncs.com/yunionio/compose-service-init:v3.10-lzx-0331.1
    volumes:
    - ./data/etc/yunion/:/etc/yunion/
    depends_on:
      mysql:
        condition: service_healthy
      keystone-post-init:
        condition: service_completed_successfully
    command:
    - /opt/yunion/bin/compose-service-init
    - --config-dir=/
    - --component=logger
    - --step=init
    - --mysql-host=mysql
    - --mysql-port=3306
    - --mysql-user=root
    - --mysql-password=your-sql-password
  logger:
    image: registry.cn-beijing.aliyuncs.com/yunionio/logger:v3.10.6
    volumes:
    - ./data/etc/yunion/pki/:/etc/yunion/pki/:ro
    - ./data/etc/yunion/logger.conf:/etc/yunion/logger.conf:ro
    depends_on:
      logger-init:
        condition: service_completed_successfully
      mysql:
        condition: service_started
    command:
    - /opt/yunion/bin/logger
    - --config
    - /etc/yunion/logger.conf
    - --auto-sync-table
    healthcheck:
      test: netstat -tln | grep -c 30999
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 30s
    restart: on-failure
  logger-post-init:
    image: registry.cn-beijing.aliyuncs.com/yunionio/compose-service-init:v3.10-lzx-0331.1
    volumes:
    - ./data/etc/yunion/:/etc/yunion/
    depends_on:
      mysql:
        condition: service_healthy
      logger:
        condition: service_healthy
    command:
    - /opt/yunion/bin/compose-service-init
    - --config-dir=/
    - --component=logger
    - --step=post-init
    - --mysql-host=mysql
    - --mysql-port=3306
    - --mysql-user=root
    - --mysql-password=your-sql-password
    restart: on-failure
  notify-init:
    image: registry.cn-beijing.aliyuncs.com/yunionio/compose-service-init:v3.10-lzx-0331.1
    volumes:
    - ./data/etc/yunion/:/etc/yunion/
    depends_on:
      mysql:
        condition: service_healthy
      keystone-post-init:
        condition: service_completed_successfully
    command:
    - /opt/yunion/bin/compose-service-init
    - --config-dir=/
    - --component=notify
    - --step=init
    - --mysql-host=mysql
    - --mysql-port=3306
    - --mysql-user=root
    - --mysql-password=your-sql-password
  notify:
    image: registry.cn-beijing.aliyuncs.com/yunionio/notify:v3.10.6
    volumes:
    - ./data/etc/yunion/pki/:/etc/yunion/pki/:ro
    - ./data/etc/yunion/notify.conf:/etc/yunion/notify.conf:ro
    depends_on:
      notify-init:
        condition: service_completed_successfully
      mysql:
        condition: service_started
    command:
    - /opt/yunion/bin/notify
    - --config
    - /etc/yunion/notify.conf
    - --auto-sync-table
    healthcheck:
      test: netstat -tln | grep -c 30777
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 30s
    restart: on-failure
  notify-post-init:
    image: registry.cn-beijing.aliyuncs.com/yunionio/compose-service-init:v3.10-lzx-0331.1
    volumes:
    - ./data/etc/yunion/:/etc/yunion/
    depends_on:
      mysql:
        condition: service_healthy
      notify:
        condition: service_healthy
    command:
    - /opt/yunion/bin/compose-service-init
    - --config-dir=/
    - --component=notify
    - --step=post-init
    - --mysql-host=mysql
    - --mysql-port=3306
    - --mysql-user=root
    - --mysql-password=your-sql-password
    restart: on-failure
  influxdb-init:
    image: registry.cn-beijing.aliyuncs.com/yunionio/compose-service-init:v3.10-lzx-0331.1
    volumes:
    - ./data/etc/yunion/:/etc/yunion/
    depends_on:
      keystone-post-init:
        condition: service_completed_successfully
    command:
    - /opt/yunion/bin/compose-service-init
    - --config-dir=/
    - --component=influxdb
    - --step=init
  influxdb:
    image: registry.cn-beijing.aliyuncs.com/yunionio/influxdb:1.7.7
    volumes:
    - ./data/etc/yunion/pki/:/etc/yunion/pki/:ro
    - ./data/etc/yunion/influxdb.conf:/etc/yunion/influxdb.conf:ro
    - ./data/var/lib/influxdb:/var/lib/influxdb
    depends_on:
      influxdb-init:
        condition: service_completed_successfully
    command:
    - influxd
    - -config
    - /etc/yunion/influxdb.conf
    healthcheck:
      test: curl -k https://localhost:30086
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 30s
    restart: on-failure
  influxdb-post-init:
    image: registry.cn-beijing.aliyuncs.com/yunionio/compose-service-init:v3.10-lzx-0331.1
    volumes:
    - ./data/etc/yunion/:/etc/yunion/
    depends_on:
      influxdb:
        condition: service_healthy
    command:
    - /opt/yunion/bin/compose-service-init
    - --config-dir=/
    - --component=influxdb
    - --step=post-init
    restart: on-failure
  region-init:
    image: registry.cn-beijing.aliyuncs.com/yunionio/compose-service-init:v3.10-lzx-0331.1
    volumes:
    - ./data/etc/yunion/:/etc/yunion/
    depends_on:
      mysql:
        condition: service_healthy
      keystone-post-init:
        condition: service_completed_successfully
    command:
    - /opt/yunion/bin/compose-service-init
    - --config-dir=/
    - --component=region
    - --step=init
    - --mysql-host=mysql
    - --mysql-port=3306
    - --mysql-user=root
    - --mysql-password=your-sql-password
  region:
    image: crpi-5xevxsf5bgb3t0ps.cn-hongkong.personal.cr.aliyuncs.com/yunionio1021/region:1.0
    volumes:
    - ./data/etc/yunion/pki/:/etc/yunion/pki/:ro
    - ./data/etc/yunion/region.conf:/etc/yunion/region.conf:ro
    depends_on:
      region-init:
        condition: service_completed_successfully
      mysql:
        condition: service_started
    command:
    - /opt/yunion/bin/region
    - --config
    - /etc/yunion/region.conf
    - --auto-sync-table
    healthcheck:
      test: netstat -tln | grep -c 30888
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 30s
    restart: on-failure
  region-post-init:
    image: registry.cn-beijing.aliyuncs.com/yunionio/compose-service-init:v3.10-lzx-0331.1
    volumes:
    - ./data/etc/yunion/:/etc/yunion/
    depends_on:
      mysql:
        condition: service_healthy
      region:
        condition: service_healthy
    command:
    - /opt/yunion/bin/compose-service-init
    - --config-dir=/
    - --component=region
    - --step=post-init
    - --mysql-host=mysql
    - --mysql-port=3306
    - --mysql-user=root
    - --mysql-password=your-sql-password
    restart: on-failure
  scheduler-init:
    image: registry.cn-beijing.aliyuncs.com/yunionio/compose-service-init:v3.10-lzx-0331.1
    volumes:
    - ./data/etc/yunion/:/etc/yunion/
    depends_on:
      mysql:
        condition: service_healthy
      region-post-init:
        condition: service_completed_successfully
    command:
    - /opt/yunion/bin/compose-service-init
    - --config-dir=/
    - --component=scheduler
    - --step=init
    - --mysql-host=mysql
    - --mysql-port=3306
    - --mysql-user=root
    - --mysql-password=your-sql-password
  scheduler:
    image: registry.cn-beijing.aliyuncs.com/yunionio/scheduler:v3.10.6
    volumes:
    - ./data/etc/yunion/pki/:/etc/yunion/pki/:ro
    - ./data/etc/yunion/scheduler.conf:/etc/yunion/scheduler.conf:ro
    depends_on:
      scheduler-init:
        condition: service_completed_successfully
      mysql:
        condition: service_started
    command:
    - /opt/yunion/bin/scheduler
    - --config
    - /etc/yunion/scheduler.conf
    healthcheck:
      test: netstat -tln | grep -c 30887
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 30s
    restart: on-failure
  scheduler-post-init:
    image: registry.cn-beijing.aliyuncs.com/yunionio/compose-service-init:v3.10-lzx-0331.1
    volumes:
    - ./data/etc/yunion/:/etc/yunion/
    depends_on:
      mysql:
        condition: service_healthy
      scheduler:
        condition: service_healthy
    command:
    - /opt/yunion/bin/compose-service-init
    - --config-dir=/
    - --component=scheduler
    - --step=post-init
    - --mysql-host=mysql
    - --mysql-port=3306
    - --mysql-user=root
    - --mysql-password=your-sql-password
    restart: on-failure
  scheduledtask-init:
    image: registry.cn-beijing.aliyuncs.com/yunionio/compose-service-init:v3.10-lzx-0331.1
    volumes:
    - ./data/etc/yunion/:/etc/yunion/
    depends_on:
      mysql:
        condition: service_healthy
      region-post-init:
        condition: service_completed_successfully
    command:
    - /opt/yunion/bin/compose-service-init
    - --config-dir=/
    - --component=scheduledtask
    - --step=init
    - --mysql-host=mysql
    - --mysql-port=3306
    - --mysql-user=root
    - --mysql-password=your-sql-password
  scheduledtask:
    image: registry.cn-beijing.aliyuncs.com/yunionio/scheduledtask:v3.10.6
    volumes:
    - ./data/etc/yunion/pki/:/etc/yunion/pki/:ro
    - ./data/etc/yunion/scheduledtask.conf:/etc/yunion/scheduledtask.conf:ro
    depends_on:
      scheduledtask-init:
        condition: service_completed_successfully
      mysql:
        condition: service_started
    command:
    - /opt/yunion/bin/scheduledtask
    - --config
    - /etc/yunion/scheduledtask.conf
    healthcheck:
      test: netstat -tln | grep -c 30978
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 30s
    restart: on-failure
  scheduledtask-post-init:
    image: registry.cn-beijing.aliyuncs.com/yunionio/compose-service-init:v3.10-lzx-0331.1
    volumes:
    - ./data/etc/yunion/:/etc/yunion/
    depends_on:
      mysql:
        condition: service_healthy
      scheduledtask:
        condition: service_healthy
    command:
    - /opt/yunion/bin/compose-service-init
    - --config-dir=/
    - --component=scheduledtask
    - --step=post-init
    - --mysql-host=mysql
    - --mysql-port=3306
    - --mysql-user=root
    - --mysql-password=your-sql-password
    restart: on-failure
  glance-init:
    image: registry.cn-beijing.aliyuncs.com/yunionio/compose-service-init:v3.10-lzx-0331.1
    volumes:
    - ./data/etc/yunion/:/etc/yunion/
    depends_on:
      mysql:
        condition: service_healthy
      keystone-post-init:
        condition: service_completed_successfully
    command:
    - /opt/yunion/bin/compose-service-init
    - --config-dir=/
    - --component=glance
    - --step=init
    - --mysql-host=mysql
    - --mysql-port=3306
    - --mysql-user=root
    - --mysql-password=your-sql-password
  glance:
    image: registry.cn-beijing.aliyuncs.com/yunionio/glance:v3.10.6
    volumes:
    - ./data/etc/yunion/pki/:/etc/yunion/pki/:ro
    - ./data/etc/yunion/glance.conf:/etc/yunion/glance.conf:ro
    - ./data/opt/cloud/workspace/data/glance:/opt/cloud/workspace/data/glance
    depends_on:
      glance-init:
        condition: service_completed_successfully
      mysql:
        condition: service_started
    command:
    - /opt/yunion/bin/glance
    - --config
    - /etc/yunion/glance.conf
    - --auto-sync-table
    healthcheck:
      test: netstat -tln | grep -c 30292
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 30s
    restart: on-failure
  glance-post-init:
    image: registry.cn-beijing.aliyuncs.com/yunionio/compose-service-init:v3.10-lzx-0331.1
    volumes:
    - ./data/etc/yunion/:/etc/yunion/
    depends_on:
      mysql:
        condition: service_healthy
      glance:
        condition: service_healthy
    command:
    - /opt/yunion/bin/compose-service-init
    - --config-dir=/
    - --component=glance
    - --step=post-init
    - --mysql-host=mysql
    - --mysql-port=3306
    - --mysql-user=root
    - --mysql-password=your-sql-password
    restart: on-failure
  kubeserver-init:
    image: registry.cn-beijing.aliyuncs.com/yunionio/compose-service-init:v3.10-lzx-0331.1
    volumes:
    - ./data/etc/yunion/:/etc/yunion/
    depends_on:
      mysql:
        condition: service_healthy
      keystone-post-init:
        condition: service_completed_successfully
    command:
    - /opt/yunion/bin/compose-service-init
    - --config-dir=/
    - --component=kubeserver
    - --step=init
    - --mysql-host=mysql
    - --mysql-port=3306
    - --mysql-user=root
    - --mysql-password=your-sql-password
  kubeserver:
    image: registry.cn-beijing.aliyuncs.com/yunionio/kubeserver:v3.10.6
    volumes:
    - ./data/etc/yunion/pki/:/etc/yunion/pki/:ro
    - ./data/etc/yunion/kubeserver.conf:/etc/yunion/kubeserver.conf:ro
    depends_on:
      kubeserver-init:
        condition: service_completed_successfully
      mysql:
        condition: service_started
    command:
    - /opt/yunion/bin/kube-server
    - --config
    - /etc/yunion/kubeserver.conf
    - --running-mode
    - docker-compose
    healthcheck:
      test: netstat -tln | grep -c 30442
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 30s
    restart: on-failure
  kubeserver-post-init:
    image: registry.cn-beijing.aliyuncs.com/yunionio/compose-service-init:v3.10-lzx-0331.1
    volumes:
    - ./data/etc/yunion/:/etc/yunion/
    depends_on:
      mysql:
        condition: service_healthy
      kubeserver:
        condition: service_healthy
    command:
    - /opt/yunion/bin/compose-service-init
    - --config-dir=/
    - --component=kubeserver
    - --step=post-init
    - --mysql-host=mysql
    - --mysql-port=3306
    - --mysql-user=root
    - --mysql-password=your-sql-password
    restart: on-failure
  ansibleserver-init:
    image: registry.cn-beijing.aliyuncs.com/yunionio/compose-service-init:v3.10-lzx-0331.1
    volumes:
    - ./data/etc/yunion/:/etc/yunion/
    depends_on:
      mysql:
        condition: service_healthy
      keystone-post-init:
        condition: service_completed_successfully
    command:
    - /opt/yunion/bin/compose-service-init
    - --config-dir=/
    - --component=ansibleserver
    - --step=init
    - --mysql-host=mysql
    - --mysql-port=3306
    - --mysql-user=root
    - --mysql-password=your-sql-password
  ansibleserver:
    image: registry.cn-beijing.aliyuncs.com/yunionio/ansibleserver:v3.10.6
    volumes:
    - ./data/etc/yunion/pki/:/etc/yunion/pki/:ro
    - ./data/etc/yunion/ansibleserver.conf:/etc/yunion/ansibleserver.conf:ro
    depends_on:
      ansibleserver-init:
        condition: service_completed_successfully
      mysql:
        condition: service_started
    command:
    - /opt/yunion/bin/ansibleserver
    - --config
    - /etc/yunion/ansibleserver.conf
    - --auto-sync-table
    healthcheck:
      test: netstat -tln | grep -c 30890
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 30s
    restart: on-failure
  ansibleserver-post-init:
    image: registry.cn-beijing.aliyuncs.com/yunionio/compose-service-init:v3.10-lzx-0331.1
    volumes:
    - ./data/etc/yunion/:/etc/yunion/
    depends_on:
      mysql:
        condition: service_healthy
      ansibleserver:
        condition: service_healthy
    command:
    - /opt/yunion/bin/compose-service-init
    - --config-dir=/
    - --component=ansibleserver
    - --step=post-init
    - --mysql-host=mysql
    - --mysql-port=3306
    - --mysql-user=root
    - --mysql-password=your-sql-password
    restart: on-failure
  climc-init:
    image: registry.cn-beijing.aliyuncs.com/yunionio/compose-service-init:v3.10-lzx-0331.1
    volumes:
    - ./data/etc/yunion/:/etc/yunion/
    environment:
      CLIMC_DEFAULT_USER: admin
      CLIMC_DEFAULT_USER_PASSWORD: admin@123
    depends_on:
      keystone-post-init:
        condition: service_completed_successfully
      region-post-init:
        condition: service_completed_successfully
    command:
    - /opt/yunion/bin/compose-service-init
    - --config-dir=/
    - --component=climc
    - --step=init
  climc:
    image: registry.cn-beijing.aliyuncs.com/yunionio/climc:v3.10.6
    volumes:
    - ./data/etc/yunion/pki/:/etc/yunion/pki/:ro
    - ./data/etc/yunion/rcadmin:/etc/yunion/rcadmin:ro
    depends_on:
      climc-init:
        condition: service_completed_successfully
      keystone-post-init:
        condition: service_completed_successfully
    command:
    - /bin/bash
    - "/opt/climc-entrypoint.sh"
    restart: on-failure
  yunionconf-init:
    image: registry.cn-beijing.aliyuncs.com/yunionio/compose-service-init:v3.10-lzx-0331.1
    volumes:
    - ./data/etc/yunion/:/etc/yunion/
    depends_on:
      mysql:
        condition: service_healthy
      keystone-post-init:
        condition: service_completed_successfully
    command:
    - /opt/yunion/bin/compose-service-init
    - --config-dir=/
    - --component=yunionconf
    - --step=init
    - --mysql-host=mysql
    - --mysql-port=3306
    - --mysql-user=root
    - --mysql-password=your-sql-password
  yunionconf:
    image: registry.cn-beijing.aliyuncs.com/yunionio/yunionconf:v3.10.6
    volumes:
    - ./data/etc/yunion/pki/:/etc/yunion/pki/:ro
    - ./data/etc/yunion/yunionconf.conf:/etc/yunion/yunionconf.conf:ro
    depends_on:
      yunionconf-init:
        condition: service_completed_successfully
      mysql:
        condition: service_started
    command:
    - /opt/yunion/bin/yunionconf
    - --config
    - /etc/yunion/yunionconf.conf
    - --auto-sync-table
    healthcheck:
      test: netstat -tln | grep -c 30889
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 30s
    restart: on-failure
  yunionconf-post-init:
    image: registry.cn-beijing.aliyuncs.com/yunionio/compose-service-init:v3.10-lzx-0331.1
    volumes:
    - ./data/etc/yunion/:/etc/yunion/
    depends_on:
      mysql:
        condition: service_healthy
      yunionconf:
        condition: service_healthy
    command:
    - /opt/yunion/bin/compose-service-init
    - --config-dir=/
    - --component=yunionconf
    - --step=post-init
    - --mysql-host=mysql
    - --mysql-port=3306
    - --mysql-user=root
    - --mysql-password=your-sql-password
    restart: on-failure
  apigateway-init:
    image: registry.cn-beijing.aliyuncs.com/yunionio/compose-service-init:v3.10-lzx-0331.1
    volumes:
    - ./data/etc/yunion/:/etc/yunion/
    depends_on:
      keystone-post-init:
        condition: service_completed_successfully
    command:
    - /opt/yunion/bin/compose-service-init
    - --config-dir=/
    - --component=apigateway
    - --step=init
  apigateway:
    image: crpi-5xevxsf5bgb3t0ps.cn-hongkong.personal.cr.aliyuncs.com/yunionio1021/apigateway:1.0
    ports:
    - 30300:30300
    volumes:
    - ./data/etc/yunion/pki/:/etc/yunion/pki/:ro
    - ./data/etc/yunion/apigateway.conf:/etc/yunion/apigateway.conf:ro
    depends_on:
      apigateway-init:
        condition: service_completed_successfully
    command:
    - /opt/yunion/bin/apigateway
    - --config
    - /etc/yunion/apigateway.conf
    healthcheck:
      test: netstat -tln | grep -c 30300
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 30s
    restart: on-failure
  apigateway-post-init:
    image: registry.cn-beijing.aliyuncs.com/yunionio/compose-service-init:v3.10-lzx-0331.1
    volumes:
    - ./data/etc/yunion/:/etc/yunion/
    depends_on:
      apigateway:
        condition: service_healthy
    command:
    - /opt/yunion/bin/compose-service-init
    - --config-dir=/
    - --component=apigateway
    - --step=post-init
    restart: on-failure
  webconsole-init:
    image: registry.cn-beijing.aliyuncs.com/yunionio/compose-service-init:v3.10-lzx-0331.1
    volumes:
    - ./data/etc/yunion/:/etc/yunion/
    depends_on:
      mysql:
        condition: service_healthy
      keystone-post-init:
        condition: service_completed_successfully
    command:
    - /opt/yunion/bin/compose-service-init
    - --config-dir=/
    - --component=webconsole
    - --step=init
    - --mysql-host=mysql
    - --mysql-port=3306
    - --mysql-user=root
    - --mysql-password=your-sql-password
  webconsole:
    image: registry.cn-beijing.aliyuncs.com/yunionio/webconsole:v3.10.6
    volumes:
    - ./data/etc/yunion/pki/:/etc/yunion/pki/:ro
    - ./data/etc/yunion/webconsole.conf:/etc/yunion/webconsole.conf:ro
    depends_on:
      webconsole-init:
        condition: service_completed_successfully
      mysql:
        condition: service_started
    command:
    - /opt/yunion/bin/webconsole
    - --config
    - /etc/yunion/webconsole.conf
    - --auto-sync-table
    healthcheck:
      test: netstat -tln | grep -c 30899
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 30s
    restart: on-failure
  webconsole-post-init:
    image: registry.cn-beijing.aliyuncs.com/yunionio/compose-service-init:v3.10-lzx-0331.1
    volumes:
    - ./data/etc/yunion/:/etc/yunion/
    depends_on:
      mysql:
        condition: service_healthy
      webconsole:
        condition: service_healthy
    command:
    - /opt/yunion/bin/compose-service-init
    - --config-dir=/
    - --component=webconsole
    - --step=post-init
    - --mysql-host=mysql
    - --mysql-port=3306
    - --mysql-user=root
    - --mysql-password=your-sql-password
    restart: on-failure
  monitor-init:
    image: registry.cn-beijing.aliyuncs.com/yunionio/compose-service-init:v3.10-lzx-0331.1
    volumes:
    - ./data/etc/yunion/:/etc/yunion/
    depends_on:
      mysql:
        condition: service_healthy
      region-post-init:
        condition: service_completed_successfully
    command:
    - /opt/yunion/bin/compose-service-init
    - --config-dir=/
    - --component=monitor
    - --step=init
    - --mysql-host=mysql
    - --mysql-port=3306
    - --mysql-user=root
    - --mysql-password=your-sql-password
  monitor:
    image: registry.cn-beijing.aliyuncs.com/yunionio/monitor:v3.10.6
    volumes:
    - ./data/etc/yunion/pki/:/etc/yunion/pki/:ro
    - ./data/etc/yunion/monitor.conf:/etc/yunion/monitor.conf:ro
    depends_on:
      monitor-init:
        condition: service_completed_successfully
      mysql:
        condition: service_started
    command:
    - /opt/yunion/bin/monitor
    - --config
    - /etc/yunion/monitor.conf
    - --auto-sync-table
    healthcheck:
      test: netstat -tln | grep -c 30093
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 30s
    restart: on-failure
  monitor-post-init:
    image: registry.cn-beijing.aliyuncs.com/yunionio/compose-service-init:v3.10-lzx-0331.1
    volumes:
    - ./data/etc/yunion/:/etc/yunion/
    depends_on:
      mysql:
        condition: service_healthy
      monitor:
        condition: service_healthy
    command:
    - /opt/yunion/bin/compose-service-init
    - --config-dir=/
    - --component=monitor
    - --step=post-init
    - --mysql-host=mysql
    - --mysql-port=3306
    - --mysql-user=root
    - --mysql-password=your-sql-password
    restart: on-failure
  cloudmon-init:
    image: registry.cn-beijing.aliyuncs.com/yunionio/compose-service-init:v3.10-lzx-0331.1
    volumes:
    - ./data/etc/yunion/:/etc/yunion/
    depends_on:
      keystone-post-init:
        condition: service_completed_successfully
    command:
    - /opt/yunion/bin/compose-service-init
    - --config-dir=/
    - --component=cloudmon
    - --step=init
  cloudmon:
    image: registry.cn-beijing.aliyuncs.com/yunionio/cloudmon:v3.10.6
    volumes:
    - ./data/etc/yunion/pki/:/etc/yunion/pki/:ro
    - ./data/etc/yunion/cloudmon.conf:/etc/yunion/cloudmon.conf:ro
    depends_on:
      cloudmon-init:
        condition: service_completed_successfully
    command:
    - /opt/yunion/bin/cloudmon
    - --config
    - /etc/yunion/cloudmon.conf
    healthcheck:
      test: netstat -tln | grep -c 30931
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 30s
    restart: on-failure
  cloudmon-post-init:
    image: registry.cn-beijing.aliyuncs.com/yunionio/compose-service-init:v3.10-lzx-0331.1
    volumes:
    - ./data/etc/yunion/:/etc/yunion/
    depends_on:
      cloudmon:
        condition: service_healthy
    command:
    - /opt/yunion/bin/compose-service-init
    - --config-dir=/
    - --component=cloudmon
    - --step=post-init
    restart: on-failure
  web-init:
    image: registry.cn-beijing.aliyuncs.com/yunionio/compose-service-init:v3.10-lzx-0331.1
    volumes:
    - ./data/etc/yunion/:/etc/yunion/
    - ./data/etc/nginx/conf.d/:/etc/nginx/conf.d/
    command:
    - /opt/yunion/bin/compose-service-init
    - --config-dir=/
    - --component=web
    - --step=init
  web:
    image: crpi-5xevxsf5bgb3t0ps.cn-hongkong.personal.cr.aliyuncs.com/yunionio1021/web:cluodpodsWeb1.0
    ports:
    - 443:443
    volumes:
    - ./data/etc/yunion/pki/:/etc/yunion/pki/:ro
    - ./data/etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
    - ./data/cloudpodweb/:/usr/share/nginx/html/web/:ro
    depends_on:
      web-init:
        condition: service_completed_successfully
      apigateway-post-init:
        condition: service_completed_successfully
      webconsole-post-init:
        condition: service_completed_successfully
    command:
    - nginx
    - -g
    - daemon off;
    restart: on-failure
```
