### ISSUE TITLE
[求助/Help]两台ubuntu22.04，部署高可用，但是get nodes只有1个节点，二节点没有加入集群

### ISSUE THREAD

**Issue by lh-66** [yunionio/cloudpods#22780]
配置文件如下
```
# primary_master_node 表示运行 k8s 和 Cloudpods 服务的节点
primary_master_node:
  # ssh login IP
  hostname: 192.168.1.68
  # 不使用本地登录方式
  use_local: false
  # ssh login user
  user: root
  # cloudpods version
  onecloud_version: "v3.11.10"
  # mariadb connection address
  db_host: "192.168.1.25"
  # mariadb user
  db_user: "root"
  # mariadb password
  db_password: "ymwx171902"
  # mariadb port
  db_port: "3316"
  # 节点服务监听的地址，多网卡时可以指定对应网卡的地址
  node_ip: "192.168.1.68"
  # 对应 Kubernetes calico 插件默认网卡选择规则
  ip_autodetection_method: "can-reach=192.168.1.68"
  # K8s 控制节点的 IP，对应keepalived 监听的 VIP
  controlplane_host: 192.168.1.91
  # K8s 控制节点 apiserver 监听的端口
  controlplane_port: "6443"
  # 该节点作为 Cloudpods 私有云计算节点，如果不想让控制节点作为计算节点，可以设置为 false
  as_host: true
  # 虚拟机可作为 Cloudpods 内置私有云计算节点（默认为 false）。开启此项时，请确保 as_host: true
  as_host_on_vm: true
  # 产品版本，从 [Edge, CMP, FullStack] 选择一个，FullStack 会安装融合云，CMP 安装多云管理版本，Edge 安装私有云
  product_version: 'Edge'
  # 服务对应的镜像仓库，如果待部署的机器不在中国大陆，可以用 dockerhub 的镜像仓库：docker.io/yunion
  image_repository: registry.cn-beijing.aliyuncs.com/yunion
  # 启用高可用模式
  high_availability: true
  # 使用 minio 作为后端虚拟机镜像存储
  enable_minio: false
  ha_using_local_registry: false
  # 计算节点默认网桥 br0 对应的网卡
  host_networks: "ens160/br0/192.168.1.68"
master_nodes:
  # 加入控制节点的 k8s vip
  controlplane_host: 192.168.1.91
  # 加入控制节点的 K8s apiserver 端口
  controlplane_port: "6443"
  # 作为 K8s 和 Cloudpods 控制节点
  as_controller: true
  # 该节点作为 Cloudpods 私有云计算节点，如果不想让控制节点作为计算节点，可以设置为 false
  as_host: true
  # 虚拟机可作为 Cloudpods 内置私有云计算节点（默认为 false）。开启此项时，请确保 as_host: true
  as_host_on_vm: true
  # 从 primary 节点同步 ntp 时间
  ntpd_server: "192.168.1.68"
  # 启用高可用模式
  high_availability: true
  hosts:
  - user: root
    hostname: "192.168.1.74"
    # 计算节点默认网桥 br0 对应的网卡
    host_networks: "ens160/br0/192.168.1.74"
```
